// Code generated by Fern. DO NOT EDIT.

package integrations

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListAllIntegrations(
	ctx context.Context,
	request *foru_ms_sdk.GetIntegrationsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetIntegrationsResponse, error) {
	response, err := c.WithRawResponse.ListAllIntegrations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateAnIntegration(
	ctx context.Context,
	request *foru_ms_sdk.PostIntegrationsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostIntegrationsResponse, error) {
	response, err := c.WithRawResponse.CreateAnIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAnIntegration(
	ctx context.Context,
	request *foru_ms_sdk.GetIntegrationsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetIntegrationsIDResponse, error) {
	response, err := c.WithRawResponse.GetAnIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAnIntegration(
	ctx context.Context,
	request *foru_ms_sdk.DeleteIntegrationsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteIntegrationsIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAnIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateAnIntegration(
	ctx context.Context,
	request *foru_ms_sdk.PatchIntegrationsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PatchIntegrationsIDResponse, error) {
	response, err := c.WithRawResponse.UpdateAnIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
