// Code generated by Fern. DO NOT EDIT.

package foru_ms_sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/foru-ms/go-sdk/internal"
	big "math/big"
)

var (
	createNotificationsRequestFieldUserID           = big.NewInt(1 << 0)
	createNotificationsRequestFieldNotifierID       = big.NewInt(1 << 1)
	createNotificationsRequestFieldType             = big.NewInt(1 << 2)
	createNotificationsRequestFieldDescription      = big.NewInt(1 << 3)
	createNotificationsRequestFieldThreadID         = big.NewInt(1 << 4)
	createNotificationsRequestFieldPostID           = big.NewInt(1 << 5)
	createNotificationsRequestFieldPrivateMessageID = big.NewInt(1 << 6)
	createNotificationsRequestFieldStatus           = big.NewInt(1 << 7)
	createNotificationsRequestFieldExtendedData     = big.NewInt(1 << 8)
)

type CreateNotificationsRequest struct {
	// Target user ID to receive notification (maps to userId)
	UserID string `json:"userId" url:"-"`
	// User ID who triggered the notification (optional, defaults to authenticated user)
	NotifierID *string `json:"notifierId,omitempty" url:"-"`
	// Notification type (e.g. mention, reply, follow)
	Type string `json:"type" url:"-"`
	// Notification text content
	Description *string `json:"description,omitempty" url:"-"`
	// Related thread ID
	ThreadID *string `json:"threadId,omitempty" url:"-"`
	// Related post ID
	PostID *string `json:"postId,omitempty" url:"-"`
	// Related private message ID
	PrivateMessageID *string `json:"privateMessageId,omitempty" url:"-"`
	// Initial notification status
	Status *CreateNotificationsRequestStatus `json:"status,omitempty" url:"-"`
	// Additional notification data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateNotificationsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetUserID(userID string) {
	c.UserID = userID
	c.require(createNotificationsRequestFieldUserID)
}

// SetNotifierID sets the NotifierID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetNotifierID(notifierID *string) {
	c.NotifierID = notifierID
	c.require(createNotificationsRequestFieldNotifierID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetType(type_ string) {
	c.Type = type_
	c.require(createNotificationsRequestFieldType)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createNotificationsRequestFieldDescription)
}

// SetThreadID sets the ThreadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetThreadID(threadID *string) {
	c.ThreadID = threadID
	c.require(createNotificationsRequestFieldThreadID)
}

// SetPostID sets the PostID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetPostID(postID *string) {
	c.PostID = postID
	c.require(createNotificationsRequestFieldPostID)
}

// SetPrivateMessageID sets the PrivateMessageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetPrivateMessageID(privateMessageID *string) {
	c.PrivateMessageID = privateMessageID
	c.require(createNotificationsRequestFieldPrivateMessageID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetStatus(status *CreateNotificationsRequestStatus) {
	c.Status = status
	c.require(createNotificationsRequestFieldStatus)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNotificationsRequest) SetExtendedData(extendedData map[string]interface{}) {
	c.ExtendedData = extendedData
	c.require(createNotificationsRequestFieldExtendedData)
}

var (
	deleteNotificationsRequestFieldID = big.NewInt(1 << 0)
)

type DeleteNotificationsRequest struct {
	// Notification ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteNotificationsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteNotificationsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteNotificationsRequestFieldID)
}

var (
	listNotificationsRequestFieldLimit  = big.NewInt(1 << 0)
	listNotificationsRequestFieldCursor = big.NewInt(1 << 1)
	listNotificationsRequestFieldStatus = big.NewInt(1 << 2)
	listNotificationsRequestFieldUserID = big.NewInt(1 << 3)
)

type ListNotificationsRequest struct {
	// Items per page (max 75)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Cursor for pagination
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Filter by notification status
	Status *ListNotificationsRequestStatus `json:"-" url:"status,omitempty"`
	// Filter by recipient user ID (admin only)
	UserID *string `json:"-" url:"userId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListNotificationsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListNotificationsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listNotificationsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListNotificationsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listNotificationsRequestFieldCursor)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListNotificationsRequest) SetStatus(status *ListNotificationsRequestStatus) {
	l.Status = status
	l.require(listNotificationsRequestFieldStatus)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListNotificationsRequest) SetUserID(userID *string) {
	l.UserID = userID
	l.require(listNotificationsRequestFieldUserID)
}

var (
	retrieveNotificationsRequestFieldID = big.NewInt(1 << 0)
)

type RetrieveNotificationsRequest struct {
	// Notification ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveNotificationsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveNotificationsRequest) SetID(id string) {
	r.ID = id
	r.require(retrieveNotificationsRequestFieldID)
}

var (
	notificationListResponseFieldData = big.NewInt(1 << 0)
)

type NotificationListResponse struct {
	Data *NotificationListResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationListResponse) GetData() *NotificationListResponseData {
	if n == nil {
		return nil
	}
	return n.Data
}

func (n *NotificationListResponse) GetExtraProperties() map[string]interface{} {
	return n.extraProperties
}

func (n *NotificationListResponse) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponse) SetData(data *NotificationListResponseData) {
	n.Data = data
	n.require(notificationListResponseFieldData)
}

func (n *NotificationListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationListResponse) MarshalJSON() ([]byte, error) {
	type embed NotificationListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationListResponse) String() string {
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	notificationListResponseDataFieldItems      = big.NewInt(1 << 0)
	notificationListResponseDataFieldNextCursor = big.NewInt(1 << 1)
	notificationListResponseDataFieldCount      = big.NewInt(1 << 2)
)

type NotificationListResponseData struct {
	Items []*NotificationListResponseDataItemsItem `json:"items" url:"items"`
	// Cursor for next page
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	// Total count of items
	Count int `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationListResponseData) GetItems() []*NotificationListResponseDataItemsItem {
	if n == nil {
		return nil
	}
	return n.Items
}

func (n *NotificationListResponseData) GetNextCursor() *string {
	if n == nil {
		return nil
	}
	return n.NextCursor
}

func (n *NotificationListResponseData) GetCount() int {
	if n == nil {
		return 0
	}
	return n.Count
}

func (n *NotificationListResponseData) GetExtraProperties() map[string]interface{} {
	return n.extraProperties
}

func (n *NotificationListResponseData) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseData) SetItems(items []*NotificationListResponseDataItemsItem) {
	n.Items = items
	n.require(notificationListResponseDataFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseData) SetNextCursor(nextCursor *string) {
	n.NextCursor = nextCursor
	n.require(notificationListResponseDataFieldNextCursor)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseData) SetCount(count int) {
	n.Count = count
	n.require(notificationListResponseDataFieldCount)
}

func (n *NotificationListResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationListResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationListResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationListResponseData) MarshalJSON() ([]byte, error) {
	type embed NotificationListResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationListResponseData) String() string {
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	notificationListResponseDataItemsItemFieldID               = big.NewInt(1 << 0)
	notificationListResponseDataItemsItemFieldUserID           = big.NewInt(1 << 1)
	notificationListResponseDataItemsItemFieldNotifierID       = big.NewInt(1 << 2)
	notificationListResponseDataItemsItemFieldType             = big.NewInt(1 << 3)
	notificationListResponseDataItemsItemFieldDescription      = big.NewInt(1 << 4)
	notificationListResponseDataItemsItemFieldStatus           = big.NewInt(1 << 5)
	notificationListResponseDataItemsItemFieldThreadID         = big.NewInt(1 << 6)
	notificationListResponseDataItemsItemFieldPostID           = big.NewInt(1 << 7)
	notificationListResponseDataItemsItemFieldPrivateMessageID = big.NewInt(1 << 8)
	notificationListResponseDataItemsItemFieldExtendedData     = big.NewInt(1 << 9)
	notificationListResponseDataItemsItemFieldCreatedAt        = big.NewInt(1 << 10)
	notificationListResponseDataItemsItemFieldUpdatedAt        = big.NewInt(1 << 11)
)

type NotificationListResponseDataItemsItem struct {
	ID string `json:"id" url:"id"`
	// Recipient user ID
	UserID string `json:"userId" url:"userId"`
	// User ID who triggered the notification
	NotifierID string `json:"notifierId" url:"notifierId"`
	// Notification type
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Notification text content
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Notification status (read, unread, dismissed, archived)
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Related thread ID
	ThreadID *string `json:"threadId,omitempty" url:"threadId,omitempty"`
	// Related post ID
	PostID *string `json:"postId,omitempty" url:"postId,omitempty"`
	// Related private message ID
	PrivateMessageID *string `json:"privateMessageId,omitempty" url:"privateMessageId,omitempty"`
	// Additional notification data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	// Notification creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Notification last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationListResponseDataItemsItem) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NotificationListResponseDataItemsItem) GetUserID() string {
	if n == nil {
		return ""
	}
	return n.UserID
}

func (n *NotificationListResponseDataItemsItem) GetNotifierID() string {
	if n == nil {
		return ""
	}
	return n.NotifierID
}

func (n *NotificationListResponseDataItemsItem) GetType() *string {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *NotificationListResponseDataItemsItem) GetDescription() *string {
	if n == nil {
		return nil
	}
	return n.Description
}

func (n *NotificationListResponseDataItemsItem) GetStatus() *string {
	if n == nil {
		return nil
	}
	return n.Status
}

func (n *NotificationListResponseDataItemsItem) GetThreadID() *string {
	if n == nil {
		return nil
	}
	return n.ThreadID
}

func (n *NotificationListResponseDataItemsItem) GetPostID() *string {
	if n == nil {
		return nil
	}
	return n.PostID
}

func (n *NotificationListResponseDataItemsItem) GetPrivateMessageID() *string {
	if n == nil {
		return nil
	}
	return n.PrivateMessageID
}

func (n *NotificationListResponseDataItemsItem) GetExtendedData() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.ExtendedData
}

func (n *NotificationListResponseDataItemsItem) GetCreatedAt() string {
	if n == nil {
		return ""
	}
	return n.CreatedAt
}

func (n *NotificationListResponseDataItemsItem) GetUpdatedAt() string {
	if n == nil {
		return ""
	}
	return n.UpdatedAt
}

func (n *NotificationListResponseDataItemsItem) GetExtraProperties() map[string]interface{} {
	return n.extraProperties
}

func (n *NotificationListResponseDataItemsItem) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetID(id string) {
	n.ID = id
	n.require(notificationListResponseDataItemsItemFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetUserID(userID string) {
	n.UserID = userID
	n.require(notificationListResponseDataItemsItemFieldUserID)
}

// SetNotifierID sets the NotifierID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetNotifierID(notifierID string) {
	n.NotifierID = notifierID
	n.require(notificationListResponseDataItemsItemFieldNotifierID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetType(type_ *string) {
	n.Type = type_
	n.require(notificationListResponseDataItemsItemFieldType)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetDescription(description *string) {
	n.Description = description
	n.require(notificationListResponseDataItemsItemFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetStatus(status *string) {
	n.Status = status
	n.require(notificationListResponseDataItemsItemFieldStatus)
}

// SetThreadID sets the ThreadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetThreadID(threadID *string) {
	n.ThreadID = threadID
	n.require(notificationListResponseDataItemsItemFieldThreadID)
}

// SetPostID sets the PostID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetPostID(postID *string) {
	n.PostID = postID
	n.require(notificationListResponseDataItemsItemFieldPostID)
}

// SetPrivateMessageID sets the PrivateMessageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetPrivateMessageID(privateMessageID *string) {
	n.PrivateMessageID = privateMessageID
	n.require(notificationListResponseDataItemsItemFieldPrivateMessageID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetExtendedData(extendedData map[string]interface{}) {
	n.ExtendedData = extendedData
	n.require(notificationListResponseDataItemsItemFieldExtendedData)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetCreatedAt(createdAt string) {
	n.CreatedAt = createdAt
	n.require(notificationListResponseDataItemsItemFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationListResponseDataItemsItem) SetUpdatedAt(updatedAt string) {
	n.UpdatedAt = updatedAt
	n.require(notificationListResponseDataItemsItemFieldUpdatedAt)
}

func (n *NotificationListResponseDataItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationListResponseDataItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationListResponseDataItemsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationListResponseDataItemsItem) MarshalJSON() ([]byte, error) {
	type embed NotificationListResponseDataItemsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationListResponseDataItemsItem) String() string {
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	notificationResponseFieldData = big.NewInt(1 << 0)
)

type NotificationResponse struct {
	Data *NotificationResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationResponse) GetData() *NotificationResponseData {
	if n == nil {
		return nil
	}
	return n.Data
}

func (n *NotificationResponse) GetExtraProperties() map[string]interface{} {
	return n.extraProperties
}

func (n *NotificationResponse) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponse) SetData(data *NotificationResponseData) {
	n.Data = data
	n.require(notificationResponseFieldData)
}

func (n *NotificationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationResponse) MarshalJSON() ([]byte, error) {
	type embed NotificationResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationResponse) String() string {
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	notificationResponseDataFieldID               = big.NewInt(1 << 0)
	notificationResponseDataFieldUserID           = big.NewInt(1 << 1)
	notificationResponseDataFieldNotifierID       = big.NewInt(1 << 2)
	notificationResponseDataFieldType             = big.NewInt(1 << 3)
	notificationResponseDataFieldDescription      = big.NewInt(1 << 4)
	notificationResponseDataFieldStatus           = big.NewInt(1 << 5)
	notificationResponseDataFieldThreadID         = big.NewInt(1 << 6)
	notificationResponseDataFieldPostID           = big.NewInt(1 << 7)
	notificationResponseDataFieldPrivateMessageID = big.NewInt(1 << 8)
	notificationResponseDataFieldExtendedData     = big.NewInt(1 << 9)
	notificationResponseDataFieldCreatedAt        = big.NewInt(1 << 10)
	notificationResponseDataFieldUpdatedAt        = big.NewInt(1 << 11)
)

type NotificationResponseData struct {
	ID string `json:"id" url:"id"`
	// Recipient user ID
	UserID string `json:"userId" url:"userId"`
	// User ID who triggered the notification
	NotifierID string `json:"notifierId" url:"notifierId"`
	// Notification type
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Notification text content
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Notification status (read, unread, dismissed, archived)
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Related thread ID
	ThreadID *string `json:"threadId,omitempty" url:"threadId,omitempty"`
	// Related post ID
	PostID *string `json:"postId,omitempty" url:"postId,omitempty"`
	// Related private message ID
	PrivateMessageID *string `json:"privateMessageId,omitempty" url:"privateMessageId,omitempty"`
	// Additional notification data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	// Notification creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Notification last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationResponseData) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NotificationResponseData) GetUserID() string {
	if n == nil {
		return ""
	}
	return n.UserID
}

func (n *NotificationResponseData) GetNotifierID() string {
	if n == nil {
		return ""
	}
	return n.NotifierID
}

func (n *NotificationResponseData) GetType() *string {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *NotificationResponseData) GetDescription() *string {
	if n == nil {
		return nil
	}
	return n.Description
}

func (n *NotificationResponseData) GetStatus() *string {
	if n == nil {
		return nil
	}
	return n.Status
}

func (n *NotificationResponseData) GetThreadID() *string {
	if n == nil {
		return nil
	}
	return n.ThreadID
}

func (n *NotificationResponseData) GetPostID() *string {
	if n == nil {
		return nil
	}
	return n.PostID
}

func (n *NotificationResponseData) GetPrivateMessageID() *string {
	if n == nil {
		return nil
	}
	return n.PrivateMessageID
}

func (n *NotificationResponseData) GetExtendedData() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.ExtendedData
}

func (n *NotificationResponseData) GetCreatedAt() string {
	if n == nil {
		return ""
	}
	return n.CreatedAt
}

func (n *NotificationResponseData) GetUpdatedAt() string {
	if n == nil {
		return ""
	}
	return n.UpdatedAt
}

func (n *NotificationResponseData) GetExtraProperties() map[string]interface{} {
	return n.extraProperties
}

func (n *NotificationResponseData) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetID(id string) {
	n.ID = id
	n.require(notificationResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetUserID(userID string) {
	n.UserID = userID
	n.require(notificationResponseDataFieldUserID)
}

// SetNotifierID sets the NotifierID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetNotifierID(notifierID string) {
	n.NotifierID = notifierID
	n.require(notificationResponseDataFieldNotifierID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetType(type_ *string) {
	n.Type = type_
	n.require(notificationResponseDataFieldType)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetDescription(description *string) {
	n.Description = description
	n.require(notificationResponseDataFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetStatus(status *string) {
	n.Status = status
	n.require(notificationResponseDataFieldStatus)
}

// SetThreadID sets the ThreadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetThreadID(threadID *string) {
	n.ThreadID = threadID
	n.require(notificationResponseDataFieldThreadID)
}

// SetPostID sets the PostID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetPostID(postID *string) {
	n.PostID = postID
	n.require(notificationResponseDataFieldPostID)
}

// SetPrivateMessageID sets the PrivateMessageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetPrivateMessageID(privateMessageID *string) {
	n.PrivateMessageID = privateMessageID
	n.require(notificationResponseDataFieldPrivateMessageID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetExtendedData(extendedData map[string]interface{}) {
	n.ExtendedData = extendedData
	n.require(notificationResponseDataFieldExtendedData)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetCreatedAt(createdAt string) {
	n.CreatedAt = createdAt
	n.require(notificationResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationResponseData) SetUpdatedAt(updatedAt string) {
	n.UpdatedAt = updatedAt
	n.require(notificationResponseDataFieldUpdatedAt)
}

func (n *NotificationResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationResponseData) MarshalJSON() ([]byte, error) {
	type embed NotificationResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationResponseData) String() string {
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Initial notification status
type CreateNotificationsRequestStatus string

const (
	CreateNotificationsRequestStatusRead      CreateNotificationsRequestStatus = "read"
	CreateNotificationsRequestStatusUnread    CreateNotificationsRequestStatus = "unread"
	CreateNotificationsRequestStatusDismissed CreateNotificationsRequestStatus = "dismissed"
	CreateNotificationsRequestStatusArchived  CreateNotificationsRequestStatus = "archived"
)

func NewCreateNotificationsRequestStatusFromString(s string) (CreateNotificationsRequestStatus, error) {
	switch s {
	case "read":
		return CreateNotificationsRequestStatusRead, nil
	case "unread":
		return CreateNotificationsRequestStatusUnread, nil
	case "dismissed":
		return CreateNotificationsRequestStatusDismissed, nil
	case "archived":
		return CreateNotificationsRequestStatusArchived, nil
	}
	var t CreateNotificationsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateNotificationsRequestStatus) Ptr() *CreateNotificationsRequestStatus {
	return &c
}

type ListNotificationsRequestStatus string

const (
	ListNotificationsRequestStatusRead      ListNotificationsRequestStatus = "read"
	ListNotificationsRequestStatusUnread    ListNotificationsRequestStatus = "unread"
	ListNotificationsRequestStatusDismissed ListNotificationsRequestStatus = "dismissed"
	ListNotificationsRequestStatusArchived  ListNotificationsRequestStatus = "archived"
)

func NewListNotificationsRequestStatusFromString(s string) (ListNotificationsRequestStatus, error) {
	switch s {
	case "read":
		return ListNotificationsRequestStatusRead, nil
	case "unread":
		return ListNotificationsRequestStatusUnread, nil
	case "dismissed":
		return ListNotificationsRequestStatusDismissed, nil
	case "archived":
		return ListNotificationsRequestStatusArchived, nil
	}
	var t ListNotificationsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListNotificationsRequestStatus) Ptr() *ListNotificationsRequestStatus {
	return &l
}

// Notification status
type UpdateNotificationsRequestStatus string

const (
	UpdateNotificationsRequestStatusRead      UpdateNotificationsRequestStatus = "read"
	UpdateNotificationsRequestStatusUnread    UpdateNotificationsRequestStatus = "unread"
	UpdateNotificationsRequestStatusDismissed UpdateNotificationsRequestStatus = "dismissed"
	UpdateNotificationsRequestStatusArchived  UpdateNotificationsRequestStatus = "archived"
)

func NewUpdateNotificationsRequestStatusFromString(s string) (UpdateNotificationsRequestStatus, error) {
	switch s {
	case "read":
		return UpdateNotificationsRequestStatusRead, nil
	case "unread":
		return UpdateNotificationsRequestStatusUnread, nil
	case "dismissed":
		return UpdateNotificationsRequestStatusDismissed, nil
	case "archived":
		return UpdateNotificationsRequestStatusArchived, nil
	}
	var t UpdateNotificationsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateNotificationsRequestStatus) Ptr() *UpdateNotificationsRequestStatus {
	return &u
}

var (
	updateNotificationsResponseFieldData = big.NewInt(1 << 0)
)

type UpdateNotificationsResponse struct {
	Data *UpdateNotificationsResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNotificationsResponse) GetData() *UpdateNotificationsResponseData {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateNotificationsResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateNotificationsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponse) SetData(data *UpdateNotificationsResponseData) {
	u.Data = data
	u.require(updateNotificationsResponseFieldData)
}

func (u *UpdateNotificationsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNotificationsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNotificationsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNotificationsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateNotificationsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNotificationsResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateNotificationsResponseDataFieldID               = big.NewInt(1 << 0)
	updateNotificationsResponseDataFieldUserID           = big.NewInt(1 << 1)
	updateNotificationsResponseDataFieldNotifierID       = big.NewInt(1 << 2)
	updateNotificationsResponseDataFieldType             = big.NewInt(1 << 3)
	updateNotificationsResponseDataFieldDescription      = big.NewInt(1 << 4)
	updateNotificationsResponseDataFieldStatus           = big.NewInt(1 << 5)
	updateNotificationsResponseDataFieldThreadID         = big.NewInt(1 << 6)
	updateNotificationsResponseDataFieldPostID           = big.NewInt(1 << 7)
	updateNotificationsResponseDataFieldPrivateMessageID = big.NewInt(1 << 8)
	updateNotificationsResponseDataFieldExtendedData     = big.NewInt(1 << 9)
	updateNotificationsResponseDataFieldCreatedAt        = big.NewInt(1 << 10)
	updateNotificationsResponseDataFieldUpdatedAt        = big.NewInt(1 << 11)
)

type UpdateNotificationsResponseData struct {
	ID string `json:"id" url:"id"`
	// Recipient user ID
	UserID string `json:"userId" url:"userId"`
	// User ID who triggered the notification
	NotifierID string `json:"notifierId" url:"notifierId"`
	// Notification type
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Notification text content
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Notification status (read, unread, dismissed, archived)
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Related thread ID
	ThreadID *string `json:"threadId,omitempty" url:"threadId,omitempty"`
	// Related post ID
	PostID *string `json:"postId,omitempty" url:"postId,omitempty"`
	// Related private message ID
	PrivateMessageID *string `json:"privateMessageId,omitempty" url:"privateMessageId,omitempty"`
	// Additional notification data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	// Notification creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Notification last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateNotificationsResponseData) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateNotificationsResponseData) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpdateNotificationsResponseData) GetNotifierID() string {
	if u == nil {
		return ""
	}
	return u.NotifierID
}

func (u *UpdateNotificationsResponseData) GetType() *string {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateNotificationsResponseData) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateNotificationsResponseData) GetStatus() *string {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateNotificationsResponseData) GetThreadID() *string {
	if u == nil {
		return nil
	}
	return u.ThreadID
}

func (u *UpdateNotificationsResponseData) GetPostID() *string {
	if u == nil {
		return nil
	}
	return u.PostID
}

func (u *UpdateNotificationsResponseData) GetPrivateMessageID() *string {
	if u == nil {
		return nil
	}
	return u.PrivateMessageID
}

func (u *UpdateNotificationsResponseData) GetExtendedData() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.ExtendedData
}

func (u *UpdateNotificationsResponseData) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateNotificationsResponseData) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateNotificationsResponseData) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateNotificationsResponseData) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetID(id string) {
	u.ID = id
	u.require(updateNotificationsResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetUserID(userID string) {
	u.UserID = userID
	u.require(updateNotificationsResponseDataFieldUserID)
}

// SetNotifierID sets the NotifierID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetNotifierID(notifierID string) {
	u.NotifierID = notifierID
	u.require(updateNotificationsResponseDataFieldNotifierID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetType(type_ *string) {
	u.Type = type_
	u.require(updateNotificationsResponseDataFieldType)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetDescription(description *string) {
	u.Description = description
	u.require(updateNotificationsResponseDataFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetStatus(status *string) {
	u.Status = status
	u.require(updateNotificationsResponseDataFieldStatus)
}

// SetThreadID sets the ThreadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetThreadID(threadID *string) {
	u.ThreadID = threadID
	u.require(updateNotificationsResponseDataFieldThreadID)
}

// SetPostID sets the PostID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetPostID(postID *string) {
	u.PostID = postID
	u.require(updateNotificationsResponseDataFieldPostID)
}

// SetPrivateMessageID sets the PrivateMessageID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetPrivateMessageID(privateMessageID *string) {
	u.PrivateMessageID = privateMessageID
	u.require(updateNotificationsResponseDataFieldPrivateMessageID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetExtendedData(extendedData map[string]interface{}) {
	u.ExtendedData = extendedData
	u.require(updateNotificationsResponseDataFieldExtendedData)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updateNotificationsResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsResponseData) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updateNotificationsResponseDataFieldUpdatedAt)
}

func (u *UpdateNotificationsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateNotificationsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateNotificationsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateNotificationsResponseData) MarshalJSON() ([]byte, error) {
	type embed UpdateNotificationsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateNotificationsResponseData) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateNotificationsRequestFieldID           = big.NewInt(1 << 0)
	updateNotificationsRequestFieldStatus       = big.NewInt(1 << 1)
	updateNotificationsRequestFieldExtendedData = big.NewInt(1 << 2)
)

type UpdateNotificationsRequest struct {
	// Notification ID
	ID string `json:"-" url:"-"`
	// Notification status
	Status *UpdateNotificationsRequestStatus `json:"status,omitempty" url:"-"`
	// Update extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateNotificationsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsRequest) SetID(id string) {
	u.ID = id
	u.require(updateNotificationsRequestFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsRequest) SetStatus(status *UpdateNotificationsRequestStatus) {
	u.Status = status
	u.require(updateNotificationsRequestFieldStatus)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateNotificationsRequest) SetExtendedData(extendedData map[string]interface{}) {
	u.ExtendedData = extendedData
	u.require(updateNotificationsRequestFieldExtendedData)
}
