// Code generated by Fern. DO NOT EDIT.

package foru_ms_sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/foru-ms/go-sdk/internal"
	big "math/big"
)

var (
	postPrivateMessagesRequestFieldRecipientID  = big.NewInt(1 << 0)
	postPrivateMessagesRequestFieldSenderID     = big.NewInt(1 << 1)
	postPrivateMessagesRequestFieldTitle        = big.NewInt(1 << 2)
	postPrivateMessagesRequestFieldBody         = big.NewInt(1 << 3)
	postPrivateMessagesRequestFieldParentID     = big.NewInt(1 << 4)
	postPrivateMessagesRequestFieldExtendedData = big.NewInt(1 << 5)
)

type PostPrivateMessagesRequest struct {
	// Recipient User ID
	RecipientID string `json:"recipientId" url:"-"`
	// Sender user ID (required for API key auth, ignored for JWT auth)
	SenderID *string `json:"senderId,omitempty" url:"-"`
	// Message title (optional for replies)
	Title *string `json:"title,omitempty" url:"-"`
	// Message content
	Body string `json:"body" url:"-"`
	// Parent Message ID (for replies)
	ParentID *string `json:"parentId,omitempty" url:"-"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostPrivateMessagesRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetRecipientID sets the RecipientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesRequest) SetRecipientID(recipientID string) {
	p.RecipientID = recipientID
	p.require(postPrivateMessagesRequestFieldRecipientID)
}

// SetSenderID sets the SenderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesRequest) SetSenderID(senderID *string) {
	p.SenderID = senderID
	p.require(postPrivateMessagesRequestFieldSenderID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesRequest) SetTitle(title *string) {
	p.Title = title
	p.require(postPrivateMessagesRequestFieldTitle)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesRequest) SetBody(body string) {
	p.Body = body
	p.require(postPrivateMessagesRequestFieldBody)
}

// SetParentID sets the ParentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesRequest) SetParentID(parentID *string) {
	p.ParentID = parentID
	p.require(postPrivateMessagesRequestFieldParentID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesRequest) SetExtendedData(extendedData map[string]interface{}) {
	p.ExtendedData = extendedData
	p.require(postPrivateMessagesRequestFieldExtendedData)
}

var (
	postPrivateMessagesIDRepliesRequestFieldID           = big.NewInt(1 << 0)
	postPrivateMessagesIDRepliesRequestFieldRecipientID  = big.NewInt(1 << 1)
	postPrivateMessagesIDRepliesRequestFieldSenderID     = big.NewInt(1 << 2)
	postPrivateMessagesIDRepliesRequestFieldTitle        = big.NewInt(1 << 3)
	postPrivateMessagesIDRepliesRequestFieldBody         = big.NewInt(1 << 4)
	postPrivateMessagesIDRepliesRequestFieldParentID     = big.NewInt(1 << 5)
	postPrivateMessagesIDRepliesRequestFieldExtendedData = big.NewInt(1 << 6)
)

type PostPrivateMessagesIDRepliesRequest struct {
	// Private Message ID
	ID string `json:"-" url:"-"`
	// Recipient User ID
	RecipientID string `json:"recipientId" url:"-"`
	// Sender user ID (required for API key auth, ignored for JWT auth)
	SenderID *string `json:"senderId,omitempty" url:"-"`
	// Message title (optional for replies)
	Title *string `json:"title,omitempty" url:"-"`
	// Message content
	Body string `json:"body" url:"-"`
	// Parent Message ID (for replies)
	ParentID *string `json:"parentId,omitempty" url:"-"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostPrivateMessagesIDRepliesRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetID(id string) {
	p.ID = id
	p.require(postPrivateMessagesIDRepliesRequestFieldID)
}

// SetRecipientID sets the RecipientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetRecipientID(recipientID string) {
	p.RecipientID = recipientID
	p.require(postPrivateMessagesIDRepliesRequestFieldRecipientID)
}

// SetSenderID sets the SenderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetSenderID(senderID *string) {
	p.SenderID = senderID
	p.require(postPrivateMessagesIDRepliesRequestFieldSenderID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetTitle(title *string) {
	p.Title = title
	p.require(postPrivateMessagesIDRepliesRequestFieldTitle)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetBody(body string) {
	p.Body = body
	p.require(postPrivateMessagesIDRepliesRequestFieldBody)
}

// SetParentID sets the ParentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetParentID(parentID *string) {
	p.ParentID = parentID
	p.require(postPrivateMessagesIDRepliesRequestFieldParentID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesRequest) SetExtendedData(extendedData map[string]interface{}) {
	p.ExtendedData = extendedData
	p.require(postPrivateMessagesIDRepliesRequestFieldExtendedData)
}

var (
	deletePrivateMessagesIDRequestFieldID = big.NewInt(1 << 0)
)

type DeletePrivateMessagesIDRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePrivateMessagesIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateMessagesIDRequest) SetID(id string) {
	d.ID = id
	d.require(deletePrivateMessagesIDRequestFieldID)
}

var (
	deletePrivateMessagesIDRepliesSubIDRequestFieldID    = big.NewInt(1 << 0)
	deletePrivateMessagesIDRepliesSubIDRequestFieldSubID = big.NewInt(1 << 1)
)

type DeletePrivateMessagesIDRepliesSubIDRequest struct {
	// Private Message ID
	ID string `json:"-" url:"-"`
	// Reply ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePrivateMessagesIDRepliesSubIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateMessagesIDRepliesSubIDRequest) SetID(id string) {
	d.ID = id
	d.require(deletePrivateMessagesIDRepliesSubIDRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateMessagesIDRepliesSubIDRequest) SetSubID(subID string) {
	d.SubID = subID
	d.require(deletePrivateMessagesIDRepliesSubIDRequestFieldSubID)
}

var (
	getPrivateMessagesIDRequestFieldID = big.NewInt(1 << 0)
)

type GetPrivateMessagesIDRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPrivateMessagesIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRequest) SetID(id string) {
	g.ID = id
	g.require(getPrivateMessagesIDRequestFieldID)
}

var (
	getPrivateMessagesIDRepliesSubIDRequestFieldID    = big.NewInt(1 << 0)
	getPrivateMessagesIDRepliesSubIDRequestFieldSubID = big.NewInt(1 << 1)
)

type GetPrivateMessagesIDRepliesSubIDRequest struct {
	// Private Message ID
	ID string `json:"-" url:"-"`
	// Reply ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPrivateMessagesIDRepliesSubIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesSubIDRequest) SetID(id string) {
	g.ID = id
	g.require(getPrivateMessagesIDRepliesSubIDRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesSubIDRequest) SetSubID(subID string) {
	g.SubID = subID
	g.require(getPrivateMessagesIDRepliesSubIDRequestFieldSubID)
}

var (
	getPrivateMessagesRequestFieldPage   = big.NewInt(1 << 0)
	getPrivateMessagesRequestFieldLimit  = big.NewInt(1 << 1)
	getPrivateMessagesRequestFieldSearch = big.NewInt(1 << 2)
)

type GetPrivateMessagesRequest struct {
	Page   *int    `json:"-" url:"page,omitempty"`
	Limit  *int    `json:"-" url:"limit,omitempty"`
	Search *string `json:"-" url:"search,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPrivateMessagesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesRequest) SetPage(page *int) {
	g.Page = page
	g.require(getPrivateMessagesRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getPrivateMessagesRequestFieldLimit)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesRequest) SetSearch(search *string) {
	g.Search = search
	g.require(getPrivateMessagesRequestFieldSearch)
}

var (
	getPrivateMessagesIDRepliesRequestFieldID     = big.NewInt(1 << 0)
	getPrivateMessagesIDRepliesRequestFieldCursor = big.NewInt(1 << 1)
	getPrivateMessagesIDRepliesRequestFieldLimit  = big.NewInt(1 << 2)
)

type GetPrivateMessagesIDRepliesRequest struct {
	// Private Message ID
	ID string `json:"-" url:"-"`
	// Pagination cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Items per page
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPrivateMessagesIDRepliesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesRequest) SetID(id string) {
	g.ID = id
	g.require(getPrivateMessagesIDRepliesRequestFieldID)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getPrivateMessagesIDRepliesRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getPrivateMessagesIDRepliesRequestFieldLimit)
}

var (
	deletePrivateMessagesIDRepliesSubIDResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeletePrivateMessagesIDRepliesSubIDResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeletePrivateMessagesIDRepliesSubIDResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeletePrivateMessagesIDRepliesSubIDResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeletePrivateMessagesIDRepliesSubIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateMessagesIDRepliesSubIDResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deletePrivateMessagesIDRepliesSubIDResponseFieldSuccess)
}

func (d *DeletePrivateMessagesIDRepliesSubIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeletePrivateMessagesIDRepliesSubIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeletePrivateMessagesIDRepliesSubIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeletePrivateMessagesIDRepliesSubIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeletePrivateMessagesIDRepliesSubIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeletePrivateMessagesIDRepliesSubIDResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deletePrivateMessagesIDResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeletePrivateMessagesIDResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeletePrivateMessagesIDResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeletePrivateMessagesIDResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeletePrivateMessagesIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePrivateMessagesIDResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deletePrivateMessagesIDResponseFieldSuccess)
}

func (d *DeletePrivateMessagesIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeletePrivateMessagesIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeletePrivateMessagesIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeletePrivateMessagesIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeletePrivateMessagesIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeletePrivateMessagesIDResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getPrivateMessagesIDRepliesResponseFieldData = big.NewInt(1 << 0)
)

type GetPrivateMessagesIDRepliesResponse struct {
	Data *GetPrivateMessagesIDRepliesResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDRepliesResponse) GetData() *GetPrivateMessagesIDRepliesResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetPrivateMessagesIDRepliesResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDRepliesResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesResponse) SetData(data *GetPrivateMessagesIDRepliesResponseData) {
	g.Data = data
	g.require(getPrivateMessagesIDRepliesResponseFieldData)
}

func (g *GetPrivateMessagesIDRepliesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDRepliesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDRepliesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDRepliesResponse) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDRepliesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDRepliesResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesIDRepliesResponseDataFieldItems      = big.NewInt(1 << 0)
	getPrivateMessagesIDRepliesResponseDataFieldNextCursor = big.NewInt(1 << 1)
	getPrivateMessagesIDRepliesResponseDataFieldCount      = big.NewInt(1 << 2)
)

type GetPrivateMessagesIDRepliesResponseData struct {
	Items      []*GetPrivateMessagesIDRepliesResponseDataItemsItem `json:"items" url:"items"`
	NextCursor *string                                             `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	Count      int                                                 `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDRepliesResponseData) GetItems() []*GetPrivateMessagesIDRepliesResponseDataItemsItem {
	if g == nil {
		return nil
	}
	return g.Items
}

func (g *GetPrivateMessagesIDRepliesResponseData) GetNextCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextCursor
}

func (g *GetPrivateMessagesIDRepliesResponseData) GetCount() int {
	if g == nil {
		return 0
	}
	return g.Count
}

func (g *GetPrivateMessagesIDRepliesResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDRepliesResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesResponseData) SetItems(items []*GetPrivateMessagesIDRepliesResponseDataItemsItem) {
	g.Items = items
	g.require(getPrivateMessagesIDRepliesResponseDataFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesResponseData) SetNextCursor(nextCursor *string) {
	g.NextCursor = nextCursor
	g.require(getPrivateMessagesIDRepliesResponseDataFieldNextCursor)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesResponseData) SetCount(count int) {
	g.Count = count
	g.require(getPrivateMessagesIDRepliesResponseDataFieldCount)
}

func (g *GetPrivateMessagesIDRepliesResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDRepliesResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDRepliesResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDRepliesResponseData) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDRepliesResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDRepliesResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetPrivateMessagesIDRepliesResponseDataItemsItem struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDRepliesResponseDataItemsItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDRepliesResponseDataItemsItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

func (g *GetPrivateMessagesIDRepliesResponseDataItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDRepliesResponseDataItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDRepliesResponseDataItemsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDRepliesResponseDataItemsItem) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDRepliesResponseDataItemsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDRepliesResponseDataItemsItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesIDRepliesSubIDResponseFieldData = big.NewInt(1 << 0)
)

type GetPrivateMessagesIDRepliesSubIDResponse struct {
	Data *GetPrivateMessagesIDRepliesSubIDResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDRepliesSubIDResponse) GetData() *GetPrivateMessagesIDRepliesSubIDResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetPrivateMessagesIDRepliesSubIDResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDRepliesSubIDResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDRepliesSubIDResponse) SetData(data *GetPrivateMessagesIDRepliesSubIDResponseData) {
	g.Data = data
	g.require(getPrivateMessagesIDRepliesSubIDResponseFieldData)
}

func (g *GetPrivateMessagesIDRepliesSubIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDRepliesSubIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDRepliesSubIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDRepliesSubIDResponse) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDRepliesSubIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDRepliesSubIDResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetPrivateMessagesIDRepliesSubIDResponseData struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDRepliesSubIDResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDRepliesSubIDResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

func (g *GetPrivateMessagesIDRepliesSubIDResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDRepliesSubIDResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDRepliesSubIDResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDRepliesSubIDResponseData) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDRepliesSubIDResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDRepliesSubIDResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesIDResponseFieldData = big.NewInt(1 << 0)
)

type GetPrivateMessagesIDResponse struct {
	Data *GetPrivateMessagesIDResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDResponse) GetData() *GetPrivateMessagesIDResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetPrivateMessagesIDResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponse) SetData(data *GetPrivateMessagesIDResponseData) {
	g.Data = data
	g.require(getPrivateMessagesIDResponseFieldData)
}

func (g *GetPrivateMessagesIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDResponse) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesIDResponseDataFieldRecipientID  = big.NewInt(1 << 0)
	getPrivateMessagesIDResponseDataFieldSenderID     = big.NewInt(1 << 1)
	getPrivateMessagesIDResponseDataFieldTitle        = big.NewInt(1 << 2)
	getPrivateMessagesIDResponseDataFieldBody         = big.NewInt(1 << 3)
	getPrivateMessagesIDResponseDataFieldParentID     = big.NewInt(1 << 4)
	getPrivateMessagesIDResponseDataFieldExtendedData = big.NewInt(1 << 5)
	getPrivateMessagesIDResponseDataFieldID           = big.NewInt(1 << 6)
	getPrivateMessagesIDResponseDataFieldStatus       = big.NewInt(1 << 7)
	getPrivateMessagesIDResponseDataFieldCreatedAt    = big.NewInt(1 << 8)
	getPrivateMessagesIDResponseDataFieldUpdatedAt    = big.NewInt(1 << 9)
)

type GetPrivateMessagesIDResponseData struct {
	// Recipient User ID
	RecipientID string `json:"recipientId" url:"recipientId"`
	// Sender user ID (required for API key auth, ignored for JWT auth)
	SenderID *string `json:"senderId,omitempty" url:"senderId,omitempty"`
	// Message title (optional for replies)
	Title *string `json:"title,omitempty" url:"title,omitempty"`
	// Message content
	Body string `json:"body" url:"body"`
	// Parent Message ID (for replies)
	ParentID *string `json:"parentId,omitempty" url:"parentId,omitempty"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	ID           string                 `json:"id" url:"id"`
	// Message status (sent, delivered, read, archived)
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Message sent timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Message last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesIDResponseData) GetRecipientID() string {
	if g == nil {
		return ""
	}
	return g.RecipientID
}

func (g *GetPrivateMessagesIDResponseData) GetSenderID() *string {
	if g == nil {
		return nil
	}
	return g.SenderID
}

func (g *GetPrivateMessagesIDResponseData) GetTitle() *string {
	if g == nil {
		return nil
	}
	return g.Title
}

func (g *GetPrivateMessagesIDResponseData) GetBody() string {
	if g == nil {
		return ""
	}
	return g.Body
}

func (g *GetPrivateMessagesIDResponseData) GetParentID() *string {
	if g == nil {
		return nil
	}
	return g.ParentID
}

func (g *GetPrivateMessagesIDResponseData) GetExtendedData() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.ExtendedData
}

func (g *GetPrivateMessagesIDResponseData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetPrivateMessagesIDResponseData) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetPrivateMessagesIDResponseData) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetPrivateMessagesIDResponseData) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetPrivateMessagesIDResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesIDResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRecipientID sets the RecipientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetRecipientID(recipientID string) {
	g.RecipientID = recipientID
	g.require(getPrivateMessagesIDResponseDataFieldRecipientID)
}

// SetSenderID sets the SenderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetSenderID(senderID *string) {
	g.SenderID = senderID
	g.require(getPrivateMessagesIDResponseDataFieldSenderID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetTitle(title *string) {
	g.Title = title
	g.require(getPrivateMessagesIDResponseDataFieldTitle)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetBody(body string) {
	g.Body = body
	g.require(getPrivateMessagesIDResponseDataFieldBody)
}

// SetParentID sets the ParentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetParentID(parentID *string) {
	g.ParentID = parentID
	g.require(getPrivateMessagesIDResponseDataFieldParentID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetExtendedData(extendedData map[string]interface{}) {
	g.ExtendedData = extendedData
	g.require(getPrivateMessagesIDResponseDataFieldExtendedData)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetID(id string) {
	g.ID = id
	g.require(getPrivateMessagesIDResponseDataFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetStatus(status *string) {
	g.Status = status
	g.require(getPrivateMessagesIDResponseDataFieldStatus)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getPrivateMessagesIDResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesIDResponseData) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getPrivateMessagesIDResponseDataFieldUpdatedAt)
}

func (g *GetPrivateMessagesIDResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesIDResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesIDResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesIDResponseData) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesIDResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesIDResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesResponseFieldData = big.NewInt(1 << 0)
	getPrivateMessagesResponseFieldMeta = big.NewInt(1 << 1)
)

type GetPrivateMessagesResponse struct {
	Data []*GetPrivateMessagesResponseDataItem `json:"data" url:"data"`
	Meta *GetPrivateMessagesResponseMeta       `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesResponse) GetData() []*GetPrivateMessagesResponseDataItem {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetPrivateMessagesResponse) GetMeta() *GetPrivateMessagesResponseMeta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetPrivateMessagesResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponse) SetData(data []*GetPrivateMessagesResponseDataItem) {
	g.Data = data
	g.require(getPrivateMessagesResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponse) SetMeta(meta *GetPrivateMessagesResponseMeta) {
	g.Meta = meta
	g.require(getPrivateMessagesResponseFieldMeta)
}

func (g *GetPrivateMessagesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesResponse) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesResponseDataItemFieldRecipientID  = big.NewInt(1 << 0)
	getPrivateMessagesResponseDataItemFieldSenderID     = big.NewInt(1 << 1)
	getPrivateMessagesResponseDataItemFieldTitle        = big.NewInt(1 << 2)
	getPrivateMessagesResponseDataItemFieldBody         = big.NewInt(1 << 3)
	getPrivateMessagesResponseDataItemFieldParentID     = big.NewInt(1 << 4)
	getPrivateMessagesResponseDataItemFieldExtendedData = big.NewInt(1 << 5)
	getPrivateMessagesResponseDataItemFieldID           = big.NewInt(1 << 6)
	getPrivateMessagesResponseDataItemFieldStatus       = big.NewInt(1 << 7)
	getPrivateMessagesResponseDataItemFieldCreatedAt    = big.NewInt(1 << 8)
	getPrivateMessagesResponseDataItemFieldUpdatedAt    = big.NewInt(1 << 9)
)

type GetPrivateMessagesResponseDataItem struct {
	// Recipient User ID
	RecipientID string `json:"recipientId" url:"recipientId"`
	// Sender user ID (required for API key auth, ignored for JWT auth)
	SenderID *string `json:"senderId,omitempty" url:"senderId,omitempty"`
	// Message title (optional for replies)
	Title *string `json:"title,omitempty" url:"title,omitempty"`
	// Message content
	Body string `json:"body" url:"body"`
	// Parent Message ID (for replies)
	ParentID *string `json:"parentId,omitempty" url:"parentId,omitempty"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	ID           string                 `json:"id" url:"id"`
	// Message status (sent, delivered, read, archived)
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Message sent timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Message last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesResponseDataItem) GetRecipientID() string {
	if g == nil {
		return ""
	}
	return g.RecipientID
}

func (g *GetPrivateMessagesResponseDataItem) GetSenderID() *string {
	if g == nil {
		return nil
	}
	return g.SenderID
}

func (g *GetPrivateMessagesResponseDataItem) GetTitle() *string {
	if g == nil {
		return nil
	}
	return g.Title
}

func (g *GetPrivateMessagesResponseDataItem) GetBody() string {
	if g == nil {
		return ""
	}
	return g.Body
}

func (g *GetPrivateMessagesResponseDataItem) GetParentID() *string {
	if g == nil {
		return nil
	}
	return g.ParentID
}

func (g *GetPrivateMessagesResponseDataItem) GetExtendedData() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.ExtendedData
}

func (g *GetPrivateMessagesResponseDataItem) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetPrivateMessagesResponseDataItem) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetPrivateMessagesResponseDataItem) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetPrivateMessagesResponseDataItem) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetPrivateMessagesResponseDataItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesResponseDataItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRecipientID sets the RecipientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetRecipientID(recipientID string) {
	g.RecipientID = recipientID
	g.require(getPrivateMessagesResponseDataItemFieldRecipientID)
}

// SetSenderID sets the SenderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetSenderID(senderID *string) {
	g.SenderID = senderID
	g.require(getPrivateMessagesResponseDataItemFieldSenderID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetTitle(title *string) {
	g.Title = title
	g.require(getPrivateMessagesResponseDataItemFieldTitle)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetBody(body string) {
	g.Body = body
	g.require(getPrivateMessagesResponseDataItemFieldBody)
}

// SetParentID sets the ParentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetParentID(parentID *string) {
	g.ParentID = parentID
	g.require(getPrivateMessagesResponseDataItemFieldParentID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetExtendedData(extendedData map[string]interface{}) {
	g.ExtendedData = extendedData
	g.require(getPrivateMessagesResponseDataItemFieldExtendedData)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetID(id string) {
	g.ID = id
	g.require(getPrivateMessagesResponseDataItemFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetStatus(status *string) {
	g.Status = status
	g.require(getPrivateMessagesResponseDataItemFieldStatus)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getPrivateMessagesResponseDataItemFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseDataItem) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getPrivateMessagesResponseDataItemFieldUpdatedAt)
}

func (g *GetPrivateMessagesResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesResponseDataItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getPrivateMessagesResponseMetaFieldTotal = big.NewInt(1 << 0)
	getPrivateMessagesResponseMetaFieldPage  = big.NewInt(1 << 1)
	getPrivateMessagesResponseMetaFieldLimit = big.NewInt(1 << 2)
)

type GetPrivateMessagesResponseMeta struct {
	Total int `json:"total" url:"total"`
	Page  int `json:"page" url:"page"`
	Limit int `json:"limit" url:"limit"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPrivateMessagesResponseMeta) GetTotal() int {
	if g == nil {
		return 0
	}
	return g.Total
}

func (g *GetPrivateMessagesResponseMeta) GetPage() int {
	if g == nil {
		return 0
	}
	return g.Page
}

func (g *GetPrivateMessagesResponseMeta) GetLimit() int {
	if g == nil {
		return 0
	}
	return g.Limit
}

func (g *GetPrivateMessagesResponseMeta) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPrivateMessagesResponseMeta) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseMeta) SetTotal(total int) {
	g.Total = total
	g.require(getPrivateMessagesResponseMetaFieldTotal)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseMeta) SetPage(page int) {
	g.Page = page
	g.require(getPrivateMessagesResponseMetaFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPrivateMessagesResponseMeta) SetLimit(limit int) {
	g.Limit = limit
	g.require(getPrivateMessagesResponseMetaFieldLimit)
}

func (g *GetPrivateMessagesResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPrivateMessagesResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPrivateMessagesResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPrivateMessagesResponseMeta) MarshalJSON() ([]byte, error) {
	type embed GetPrivateMessagesResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPrivateMessagesResponseMeta) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	postPrivateMessagesIDRepliesResponseFieldData = big.NewInt(1 << 0)
)

type PostPrivateMessagesIDRepliesResponse struct {
	Data *PostPrivateMessagesIDRepliesResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostPrivateMessagesIDRepliesResponse) GetData() *PostPrivateMessagesIDRepliesResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PostPrivateMessagesIDRepliesResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostPrivateMessagesIDRepliesResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesIDRepliesResponse) SetData(data *PostPrivateMessagesIDRepliesResponseData) {
	p.Data = data
	p.require(postPrivateMessagesIDRepliesResponseFieldData)
}

func (p *PostPrivateMessagesIDRepliesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostPrivateMessagesIDRepliesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostPrivateMessagesIDRepliesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostPrivateMessagesIDRepliesResponse) MarshalJSON() ([]byte, error) {
	type embed PostPrivateMessagesIDRepliesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostPrivateMessagesIDRepliesResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostPrivateMessagesIDRepliesResponseData struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostPrivateMessagesIDRepliesResponseData) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostPrivateMessagesIDRepliesResponseData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

func (p *PostPrivateMessagesIDRepliesResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PostPrivateMessagesIDRepliesResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostPrivateMessagesIDRepliesResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostPrivateMessagesIDRepliesResponseData) MarshalJSON() ([]byte, error) {
	type embed PostPrivateMessagesIDRepliesResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostPrivateMessagesIDRepliesResponseData) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	postPrivateMessagesResponseFieldData = big.NewInt(1 << 0)
)

type PostPrivateMessagesResponse struct {
	Data *PostPrivateMessagesResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostPrivateMessagesResponse) GetData() *PostPrivateMessagesResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PostPrivateMessagesResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostPrivateMessagesResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponse) SetData(data *PostPrivateMessagesResponseData) {
	p.Data = data
	p.require(postPrivateMessagesResponseFieldData)
}

func (p *PostPrivateMessagesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostPrivateMessagesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostPrivateMessagesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostPrivateMessagesResponse) MarshalJSON() ([]byte, error) {
	type embed PostPrivateMessagesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostPrivateMessagesResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	postPrivateMessagesResponseDataFieldRecipientID  = big.NewInt(1 << 0)
	postPrivateMessagesResponseDataFieldSenderID     = big.NewInt(1 << 1)
	postPrivateMessagesResponseDataFieldTitle        = big.NewInt(1 << 2)
	postPrivateMessagesResponseDataFieldBody         = big.NewInt(1 << 3)
	postPrivateMessagesResponseDataFieldParentID     = big.NewInt(1 << 4)
	postPrivateMessagesResponseDataFieldExtendedData = big.NewInt(1 << 5)
	postPrivateMessagesResponseDataFieldID           = big.NewInt(1 << 6)
	postPrivateMessagesResponseDataFieldStatus       = big.NewInt(1 << 7)
	postPrivateMessagesResponseDataFieldCreatedAt    = big.NewInt(1 << 8)
	postPrivateMessagesResponseDataFieldUpdatedAt    = big.NewInt(1 << 9)
)

type PostPrivateMessagesResponseData struct {
	// Recipient User ID
	RecipientID string `json:"recipientId" url:"recipientId"`
	// Sender user ID (required for API key auth, ignored for JWT auth)
	SenderID *string `json:"senderId,omitempty" url:"senderId,omitempty"`
	// Message title (optional for replies)
	Title *string `json:"title,omitempty" url:"title,omitempty"`
	// Message content
	Body string `json:"body" url:"body"`
	// Parent Message ID (for replies)
	ParentID *string `json:"parentId,omitempty" url:"parentId,omitempty"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	ID           string                 `json:"id" url:"id"`
	// Message status (sent, delivered, read, archived)
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Message sent timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Message last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostPrivateMessagesResponseData) GetRecipientID() string {
	if p == nil {
		return ""
	}
	return p.RecipientID
}

func (p *PostPrivateMessagesResponseData) GetSenderID() *string {
	if p == nil {
		return nil
	}
	return p.SenderID
}

func (p *PostPrivateMessagesResponseData) GetTitle() *string {
	if p == nil {
		return nil
	}
	return p.Title
}

func (p *PostPrivateMessagesResponseData) GetBody() string {
	if p == nil {
		return ""
	}
	return p.Body
}

func (p *PostPrivateMessagesResponseData) GetParentID() *string {
	if p == nil {
		return nil
	}
	return p.ParentID
}

func (p *PostPrivateMessagesResponseData) GetExtendedData() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.ExtendedData
}

func (p *PostPrivateMessagesResponseData) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostPrivateMessagesResponseData) GetStatus() *string {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PostPrivateMessagesResponseData) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *PostPrivateMessagesResponseData) GetUpdatedAt() string {
	if p == nil {
		return ""
	}
	return p.UpdatedAt
}

func (p *PostPrivateMessagesResponseData) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostPrivateMessagesResponseData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetRecipientID sets the RecipientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetRecipientID(recipientID string) {
	p.RecipientID = recipientID
	p.require(postPrivateMessagesResponseDataFieldRecipientID)
}

// SetSenderID sets the SenderID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetSenderID(senderID *string) {
	p.SenderID = senderID
	p.require(postPrivateMessagesResponseDataFieldSenderID)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetTitle(title *string) {
	p.Title = title
	p.require(postPrivateMessagesResponseDataFieldTitle)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetBody(body string) {
	p.Body = body
	p.require(postPrivateMessagesResponseDataFieldBody)
}

// SetParentID sets the ParentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetParentID(parentID *string) {
	p.ParentID = parentID
	p.require(postPrivateMessagesResponseDataFieldParentID)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetExtendedData(extendedData map[string]interface{}) {
	p.ExtendedData = extendedData
	p.require(postPrivateMessagesResponseDataFieldExtendedData)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetID(id string) {
	p.ID = id
	p.require(postPrivateMessagesResponseDataFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetStatus(status *string) {
	p.Status = status
	p.require(postPrivateMessagesResponseDataFieldStatus)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetCreatedAt(createdAt string) {
	p.CreatedAt = createdAt
	p.require(postPrivateMessagesResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostPrivateMessagesResponseData) SetUpdatedAt(updatedAt string) {
	p.UpdatedAt = updatedAt
	p.require(postPrivateMessagesResponseDataFieldUpdatedAt)
}

func (p *PostPrivateMessagesResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PostPrivateMessagesResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostPrivateMessagesResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostPrivateMessagesResponseData) MarshalJSON() ([]byte, error) {
	type embed PostPrivateMessagesResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostPrivateMessagesResponseData) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
