// Code generated by Fern. DO NOT EDIT.

package foru_ms_sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/foru-ms/go-sdk/internal"
	big "math/big"
)

var (
	createTagsRequestFieldName         = big.NewInt(1 << 0)
	createTagsRequestFieldSlug         = big.NewInt(1 << 1)
	createTagsRequestFieldDescription  = big.NewInt(1 << 2)
	createTagsRequestFieldColor        = big.NewInt(1 << 3)
	createTagsRequestFieldExtendedData = big.NewInt(1 << 4)
)

type CreateTagsRequest struct {
	// Tag name
	Name string `json:"name" url:"-"`
	// Tag slug (unique identifier)
	Slug *string `json:"slug,omitempty" url:"-"`
	// Tag description
	Description *string `json:"description,omitempty" url:"-"`
	// Hex color code
	Color *string `json:"color,omitempty" url:"-"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateTagsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTagsRequest) SetName(name string) {
	c.Name = name
	c.require(createTagsRequestFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTagsRequest) SetSlug(slug *string) {
	c.Slug = slug
	c.require(createTagsRequestFieldSlug)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTagsRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createTagsRequestFieldDescription)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTagsRequest) SetColor(color *string) {
	c.Color = color
	c.require(createTagsRequestFieldColor)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTagsRequest) SetExtendedData(extendedData map[string]interface{}) {
	c.ExtendedData = extendedData
	c.require(createTagsRequestFieldExtendedData)
}

var (
	deleteTagsRequestFieldID = big.NewInt(1 << 0)
)

type DeleteTagsRequest struct {
	// Tag ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteTagsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteTagsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteTagsRequestFieldID)
}

var (
	deleteSubscriberTagsRequestFieldID    = big.NewInt(1 << 0)
	deleteSubscriberTagsRequestFieldSubID = big.NewInt(1 << 1)
)

type DeleteSubscriberTagsRequest struct {
	// Tag ID
	ID string `json:"-" url:"-"`
	// Subscriber ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSubscriberTagsRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSubscriberTagsRequest) SetID(id string) {
	d.ID = id
	d.require(deleteSubscriberTagsRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSubscriberTagsRequest) SetSubID(subID string) {
	d.SubID = subID
	d.require(deleteSubscriberTagsRequestFieldSubID)
}

var (
	listTagsRequestFieldLimit  = big.NewInt(1 << 0)
	listTagsRequestFieldCursor = big.NewInt(1 << 1)
	listTagsRequestFieldSearch = big.NewInt(1 << 2)
)

type ListTagsRequest struct {
	// Items per page (max 75)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Cursor for pagination
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Search tags by name or description
	Search *string `json:"-" url:"search,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListTagsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTagsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listTagsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTagsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listTagsRequestFieldCursor)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTagsRequest) SetSearch(search *string) {
	l.Search = search
	l.require(listTagsRequestFieldSearch)
}

var (
	listSubscribersTagsRequestFieldID     = big.NewInt(1 << 0)
	listSubscribersTagsRequestFieldLimit  = big.NewInt(1 << 1)
	listSubscribersTagsRequestFieldCursor = big.NewInt(1 << 2)
)

type ListSubscribersTagsRequest struct {
	// Tag ID
	ID string `json:"-" url:"-"`
	// Items per page (max 75)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Cursor for pagination
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSubscribersTagsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubscribersTagsRequest) SetID(id string) {
	l.ID = id
	l.require(listSubscribersTagsRequestFieldID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubscribersTagsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listSubscribersTagsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubscribersTagsRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listSubscribersTagsRequestFieldCursor)
}

var (
	retrieveTagsRequestFieldID = big.NewInt(1 << 0)
)

type RetrieveTagsRequest struct {
	// Tag ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveTagsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveTagsRequest) SetID(id string) {
	r.ID = id
	r.require(retrieveTagsRequestFieldID)
}

var (
	retrieveSubscriberTagsRequestFieldID    = big.NewInt(1 << 0)
	retrieveSubscriberTagsRequestFieldSubID = big.NewInt(1 << 1)
)

type RetrieveSubscriberTagsRequest struct {
	// Tag ID
	ID string `json:"-" url:"-"`
	// Subscriber ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveSubscriberTagsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsRequest) SetID(id string) {
	r.ID = id
	r.require(retrieveSubscriberTagsRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsRequest) SetSubID(subID string) {
	r.SubID = subID
	r.require(retrieveSubscriberTagsRequestFieldSubID)
}

var (
	tagListResponseFieldData = big.NewInt(1 << 0)
)

type TagListResponse struct {
	Data *TagListResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagListResponse) GetData() *TagListResponseData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TagListResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagListResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponse) SetData(data *TagListResponseData) {
	t.Data = data
	t.require(tagListResponseFieldData)
}

func (t *TagListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TagListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagListResponse) MarshalJSON() ([]byte, error) {
	type embed TagListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagListResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagListResponseDataFieldItems      = big.NewInt(1 << 0)
	tagListResponseDataFieldNextCursor = big.NewInt(1 << 1)
	tagListResponseDataFieldCount      = big.NewInt(1 << 2)
)

type TagListResponseData struct {
	Items []*TagListResponseDataItemsItem `json:"items" url:"items"`
	// Cursor for next page
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	// Total count of items
	Count int `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagListResponseData) GetItems() []*TagListResponseDataItemsItem {
	if t == nil {
		return nil
	}
	return t.Items
}

func (t *TagListResponseData) GetNextCursor() *string {
	if t == nil {
		return nil
	}
	return t.NextCursor
}

func (t *TagListResponseData) GetCount() int {
	if t == nil {
		return 0
	}
	return t.Count
}

func (t *TagListResponseData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagListResponseData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseData) SetItems(items []*TagListResponseDataItemsItem) {
	t.Items = items
	t.require(tagListResponseDataFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseData) SetNextCursor(nextCursor *string) {
	t.NextCursor = nextCursor
	t.require(tagListResponseDataFieldNextCursor)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseData) SetCount(count int) {
	t.Count = count
	t.require(tagListResponseDataFieldCount)
}

func (t *TagListResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler TagListResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagListResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagListResponseData) MarshalJSON() ([]byte, error) {
	type embed TagListResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagListResponseData) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagListResponseDataItemsItemFieldName         = big.NewInt(1 << 0)
	tagListResponseDataItemsItemFieldSlug         = big.NewInt(1 << 1)
	tagListResponseDataItemsItemFieldDescription  = big.NewInt(1 << 2)
	tagListResponseDataItemsItemFieldColor        = big.NewInt(1 << 3)
	tagListResponseDataItemsItemFieldExtendedData = big.NewInt(1 << 4)
	tagListResponseDataItemsItemFieldID           = big.NewInt(1 << 5)
	tagListResponseDataItemsItemFieldCreatedAt    = big.NewInt(1 << 6)
	tagListResponseDataItemsItemFieldUpdatedAt    = big.NewInt(1 << 7)
)

type TagListResponseDataItemsItem struct {
	// Tag name
	Name string `json:"name" url:"name"`
	// Tag slug (unique identifier)
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`
	// Tag description
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Hex color code
	Color *string `json:"color,omitempty" url:"color,omitempty"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	ID           string                 `json:"id" url:"id"`
	// Tag creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Tag last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagListResponseDataItemsItem) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TagListResponseDataItemsItem) GetSlug() *string {
	if t == nil {
		return nil
	}
	return t.Slug
}

func (t *TagListResponseDataItemsItem) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TagListResponseDataItemsItem) GetColor() *string {
	if t == nil {
		return nil
	}
	return t.Color
}

func (t *TagListResponseDataItemsItem) GetExtendedData() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtendedData
}

func (t *TagListResponseDataItemsItem) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TagListResponseDataItemsItem) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TagListResponseDataItemsItem) GetUpdatedAt() string {
	if t == nil {
		return ""
	}
	return t.UpdatedAt
}

func (t *TagListResponseDataItemsItem) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagListResponseDataItemsItem) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetName(name string) {
	t.Name = name
	t.require(tagListResponseDataItemsItemFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetSlug(slug *string) {
	t.Slug = slug
	t.require(tagListResponseDataItemsItemFieldSlug)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetDescription(description *string) {
	t.Description = description
	t.require(tagListResponseDataItemsItemFieldDescription)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetColor(color *string) {
	t.Color = color
	t.require(tagListResponseDataItemsItemFieldColor)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetExtendedData(extendedData map[string]interface{}) {
	t.ExtendedData = extendedData
	t.require(tagListResponseDataItemsItemFieldExtendedData)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetID(id string) {
	t.ID = id
	t.require(tagListResponseDataItemsItemFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetCreatedAt(createdAt string) {
	t.CreatedAt = createdAt
	t.require(tagListResponseDataItemsItemFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagListResponseDataItemsItem) SetUpdatedAt(updatedAt string) {
	t.UpdatedAt = updatedAt
	t.require(tagListResponseDataItemsItemFieldUpdatedAt)
}

func (t *TagListResponseDataItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler TagListResponseDataItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagListResponseDataItemsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagListResponseDataItemsItem) MarshalJSON() ([]byte, error) {
	type embed TagListResponseDataItemsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagListResponseDataItemsItem) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagResponseFieldData = big.NewInt(1 << 0)
)

type TagResponse struct {
	Data *TagResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagResponse) GetData() *TagResponseData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TagResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponse) SetData(data *TagResponseData) {
	t.Data = data
	t.require(tagResponseFieldData)
}

func (t *TagResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TagResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagResponse) MarshalJSON() ([]byte, error) {
	type embed TagResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagResponseDataFieldName         = big.NewInt(1 << 0)
	tagResponseDataFieldSlug         = big.NewInt(1 << 1)
	tagResponseDataFieldDescription  = big.NewInt(1 << 2)
	tagResponseDataFieldColor        = big.NewInt(1 << 3)
	tagResponseDataFieldExtendedData = big.NewInt(1 << 4)
	tagResponseDataFieldID           = big.NewInt(1 << 5)
	tagResponseDataFieldCreatedAt    = big.NewInt(1 << 6)
	tagResponseDataFieldUpdatedAt    = big.NewInt(1 << 7)
)

type TagResponseData struct {
	// Tag name
	Name string `json:"name" url:"name"`
	// Tag slug (unique identifier)
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`
	// Tag description
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Hex color code
	Color *string `json:"color,omitempty" url:"color,omitempty"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	ID           string                 `json:"id" url:"id"`
	// Tag creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Tag last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagResponseData) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TagResponseData) GetSlug() *string {
	if t == nil {
		return nil
	}
	return t.Slug
}

func (t *TagResponseData) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TagResponseData) GetColor() *string {
	if t == nil {
		return nil
	}
	return t.Color
}

func (t *TagResponseData) GetExtendedData() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.ExtendedData
}

func (t *TagResponseData) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TagResponseData) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TagResponseData) GetUpdatedAt() string {
	if t == nil {
		return ""
	}
	return t.UpdatedAt
}

func (t *TagResponseData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagResponseData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetName(name string) {
	t.Name = name
	t.require(tagResponseDataFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetSlug(slug *string) {
	t.Slug = slug
	t.require(tagResponseDataFieldSlug)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetDescription(description *string) {
	t.Description = description
	t.require(tagResponseDataFieldDescription)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetColor(color *string) {
	t.Color = color
	t.require(tagResponseDataFieldColor)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetExtendedData(extendedData map[string]interface{}) {
	t.ExtendedData = extendedData
	t.require(tagResponseDataFieldExtendedData)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetID(id string) {
	t.ID = id
	t.require(tagResponseDataFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetCreatedAt(createdAt string) {
	t.CreatedAt = createdAt
	t.require(tagResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagResponseData) SetUpdatedAt(updatedAt string) {
	t.UpdatedAt = updatedAt
	t.require(tagResponseDataFieldUpdatedAt)
}

func (t *TagResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler TagResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagResponseData) MarshalJSON() ([]byte, error) {
	type embed TagResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagResponseData) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagSubscriberListResponseFieldData = big.NewInt(1 << 0)
)

type TagSubscriberListResponse struct {
	Data *TagSubscriberListResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagSubscriberListResponse) GetData() *TagSubscriberListResponseData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TagSubscriberListResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagSubscriberListResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponse) SetData(data *TagSubscriberListResponseData) {
	t.Data = data
	t.require(tagSubscriberListResponseFieldData)
}

func (t *TagSubscriberListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TagSubscriberListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagSubscriberListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagSubscriberListResponse) MarshalJSON() ([]byte, error) {
	type embed TagSubscriberListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagSubscriberListResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagSubscriberListResponseDataFieldItems      = big.NewInt(1 << 0)
	tagSubscriberListResponseDataFieldNextCursor = big.NewInt(1 << 1)
	tagSubscriberListResponseDataFieldCount      = big.NewInt(1 << 2)
)

type TagSubscriberListResponseData struct {
	Items      []*TagSubscriberListResponseDataItemsItem `json:"items" url:"items"`
	NextCursor *string                                   `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	Count      int                                       `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagSubscriberListResponseData) GetItems() []*TagSubscriberListResponseDataItemsItem {
	if t == nil {
		return nil
	}
	return t.Items
}

func (t *TagSubscriberListResponseData) GetNextCursor() *string {
	if t == nil {
		return nil
	}
	return t.NextCursor
}

func (t *TagSubscriberListResponseData) GetCount() int {
	if t == nil {
		return 0
	}
	return t.Count
}

func (t *TagSubscriberListResponseData) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagSubscriberListResponseData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseData) SetItems(items []*TagSubscriberListResponseDataItemsItem) {
	t.Items = items
	t.require(tagSubscriberListResponseDataFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseData) SetNextCursor(nextCursor *string) {
	t.NextCursor = nextCursor
	t.require(tagSubscriberListResponseDataFieldNextCursor)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseData) SetCount(count int) {
	t.Count = count
	t.require(tagSubscriberListResponseDataFieldCount)
}

func (t *TagSubscriberListResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler TagSubscriberListResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagSubscriberListResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagSubscriberListResponseData) MarshalJSON() ([]byte, error) {
	type embed TagSubscriberListResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagSubscriberListResponseData) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagSubscriberListResponseDataItemsItemFieldID        = big.NewInt(1 << 0)
	tagSubscriberListResponseDataItemsItemFieldUserID    = big.NewInt(1 << 1)
	tagSubscriberListResponseDataItemsItemFieldTagID     = big.NewInt(1 << 2)
	tagSubscriberListResponseDataItemsItemFieldUser      = big.NewInt(1 << 3)
	tagSubscriberListResponseDataItemsItemFieldCreatedAt = big.NewInt(1 << 4)
)

type TagSubscriberListResponseDataItemsItem struct {
	ID        string                                      `json:"id" url:"id"`
	UserID    string                                      `json:"userId" url:"userId"`
	TagID     *string                                     `json:"tagId,omitempty" url:"tagId,omitempty"`
	User      *TagSubscriberListResponseDataItemsItemUser `json:"user,omitempty" url:"user,omitempty"`
	CreatedAt string                                      `json:"createdAt" url:"createdAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagSubscriberListResponseDataItemsItem) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TagSubscriberListResponseDataItemsItem) GetUserID() string {
	if t == nil {
		return ""
	}
	return t.UserID
}

func (t *TagSubscriberListResponseDataItemsItem) GetTagID() *string {
	if t == nil {
		return nil
	}
	return t.TagID
}

func (t *TagSubscriberListResponseDataItemsItem) GetUser() *TagSubscriberListResponseDataItemsItemUser {
	if t == nil {
		return nil
	}
	return t.User
}

func (t *TagSubscriberListResponseDataItemsItem) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TagSubscriberListResponseDataItemsItem) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagSubscriberListResponseDataItemsItem) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItem) SetID(id string) {
	t.ID = id
	t.require(tagSubscriberListResponseDataItemsItemFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItem) SetUserID(userID string) {
	t.UserID = userID
	t.require(tagSubscriberListResponseDataItemsItemFieldUserID)
}

// SetTagID sets the TagID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItem) SetTagID(tagID *string) {
	t.TagID = tagID
	t.require(tagSubscriberListResponseDataItemsItemFieldTagID)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItem) SetUser(user *TagSubscriberListResponseDataItemsItemUser) {
	t.User = user
	t.require(tagSubscriberListResponseDataItemsItemFieldUser)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItem) SetCreatedAt(createdAt string) {
	t.CreatedAt = createdAt
	t.require(tagSubscriberListResponseDataItemsItemFieldCreatedAt)
}

func (t *TagSubscriberListResponseDataItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler TagSubscriberListResponseDataItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagSubscriberListResponseDataItemsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagSubscriberListResponseDataItemsItem) MarshalJSON() ([]byte, error) {
	type embed TagSubscriberListResponseDataItemsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagSubscriberListResponseDataItemsItem) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	tagSubscriberListResponseDataItemsItemUserFieldID          = big.NewInt(1 << 0)
	tagSubscriberListResponseDataItemsItemUserFieldUsername    = big.NewInt(1 << 1)
	tagSubscriberListResponseDataItemsItemUserFieldDisplayName = big.NewInt(1 << 2)
)

type TagSubscriberListResponseDataItemsItemUser struct {
	ID          string  `json:"id" url:"id"`
	Username    string  `json:"username" url:"username"`
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TagSubscriberListResponseDataItemsItemUser) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TagSubscriberListResponseDataItemsItemUser) GetUsername() string {
	if t == nil {
		return ""
	}
	return t.Username
}

func (t *TagSubscriberListResponseDataItemsItemUser) GetDisplayName() *string {
	if t == nil {
		return nil
	}
	return t.DisplayName
}

func (t *TagSubscriberListResponseDataItemsItemUser) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TagSubscriberListResponseDataItemsItemUser) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItemUser) SetID(id string) {
	t.ID = id
	t.require(tagSubscriberListResponseDataItemsItemUserFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItemUser) SetUsername(username string) {
	t.Username = username
	t.require(tagSubscriberListResponseDataItemsItemUserFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TagSubscriberListResponseDataItemsItemUser) SetDisplayName(displayName *string) {
	t.DisplayName = displayName
	t.require(tagSubscriberListResponseDataItemsItemUserFieldDisplayName)
}

func (t *TagSubscriberListResponseDataItemsItemUser) UnmarshalJSON(data []byte) error {
	type unmarshaler TagSubscriberListResponseDataItemsItemUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TagSubscriberListResponseDataItemsItemUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TagSubscriberListResponseDataItemsItemUser) MarshalJSON() ([]byte, error) {
	type embed TagSubscriberListResponseDataItemsItemUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TagSubscriberListResponseDataItemsItemUser) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	retrieveSubscriberTagsResponseFieldData = big.NewInt(1 << 0)
)

type RetrieveSubscriberTagsResponse struct {
	Data *RetrieveSubscriberTagsResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveSubscriberTagsResponse) GetData() *RetrieveSubscriberTagsResponseData {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RetrieveSubscriberTagsResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveSubscriberTagsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponse) SetData(data *RetrieveSubscriberTagsResponseData) {
	r.Data = data
	r.require(retrieveSubscriberTagsResponseFieldData)
}

func (r *RetrieveSubscriberTagsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveSubscriberTagsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveSubscriberTagsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveSubscriberTagsResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveSubscriberTagsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveSubscriberTagsResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	retrieveSubscriberTagsResponseDataFieldID        = big.NewInt(1 << 0)
	retrieveSubscriberTagsResponseDataFieldUserID    = big.NewInt(1 << 1)
	retrieveSubscriberTagsResponseDataFieldTagID     = big.NewInt(1 << 2)
	retrieveSubscriberTagsResponseDataFieldUser      = big.NewInt(1 << 3)
	retrieveSubscriberTagsResponseDataFieldCreatedAt = big.NewInt(1 << 4)
)

type RetrieveSubscriberTagsResponseData struct {
	ID        string                                  `json:"id" url:"id"`
	UserID    string                                  `json:"userId" url:"userId"`
	TagID     *string                                 `json:"tagId,omitempty" url:"tagId,omitempty"`
	User      *RetrieveSubscriberTagsResponseDataUser `json:"user,omitempty" url:"user,omitempty"`
	CreatedAt string                                  `json:"createdAt" url:"createdAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveSubscriberTagsResponseData) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RetrieveSubscriberTagsResponseData) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

func (r *RetrieveSubscriberTagsResponseData) GetTagID() *string {
	if r == nil {
		return nil
	}
	return r.TagID
}

func (r *RetrieveSubscriberTagsResponseData) GetUser() *RetrieveSubscriberTagsResponseDataUser {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *RetrieveSubscriberTagsResponseData) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RetrieveSubscriberTagsResponseData) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveSubscriberTagsResponseData) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseData) SetID(id string) {
	r.ID = id
	r.require(retrieveSubscriberTagsResponseDataFieldID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseData) SetUserID(userID string) {
	r.UserID = userID
	r.require(retrieveSubscriberTagsResponseDataFieldUserID)
}

// SetTagID sets the TagID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseData) SetTagID(tagID *string) {
	r.TagID = tagID
	r.require(retrieveSubscriberTagsResponseDataFieldTagID)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseData) SetUser(user *RetrieveSubscriberTagsResponseDataUser) {
	r.User = user
	r.require(retrieveSubscriberTagsResponseDataFieldUser)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseData) SetCreatedAt(createdAt string) {
	r.CreatedAt = createdAt
	r.require(retrieveSubscriberTagsResponseDataFieldCreatedAt)
}

func (r *RetrieveSubscriberTagsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveSubscriberTagsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveSubscriberTagsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveSubscriberTagsResponseData) MarshalJSON() ([]byte, error) {
	type embed RetrieveSubscriberTagsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveSubscriberTagsResponseData) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	retrieveSubscriberTagsResponseDataUserFieldID          = big.NewInt(1 << 0)
	retrieveSubscriberTagsResponseDataUserFieldUsername    = big.NewInt(1 << 1)
	retrieveSubscriberTagsResponseDataUserFieldDisplayName = big.NewInt(1 << 2)
)

type RetrieveSubscriberTagsResponseDataUser struct {
	ID          string  `json:"id" url:"id"`
	Username    string  `json:"username" url:"username"`
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveSubscriberTagsResponseDataUser) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RetrieveSubscriberTagsResponseDataUser) GetUsername() string {
	if r == nil {
		return ""
	}
	return r.Username
}

func (r *RetrieveSubscriberTagsResponseDataUser) GetDisplayName() *string {
	if r == nil {
		return nil
	}
	return r.DisplayName
}

func (r *RetrieveSubscriberTagsResponseDataUser) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RetrieveSubscriberTagsResponseDataUser) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseDataUser) SetID(id string) {
	r.ID = id
	r.require(retrieveSubscriberTagsResponseDataUserFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseDataUser) SetUsername(username string) {
	r.Username = username
	r.require(retrieveSubscriberTagsResponseDataUserFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubscriberTagsResponseDataUser) SetDisplayName(displayName *string) {
	r.DisplayName = displayName
	r.require(retrieveSubscriberTagsResponseDataUserFieldDisplayName)
}

func (r *RetrieveSubscriberTagsResponseDataUser) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveSubscriberTagsResponseDataUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveSubscriberTagsResponseDataUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveSubscriberTagsResponseDataUser) MarshalJSON() ([]byte, error) {
	type embed RetrieveSubscriberTagsResponseDataUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveSubscriberTagsResponseDataUser) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	updateTagsResponseFieldData = big.NewInt(1 << 0)
)

type UpdateTagsResponse struct {
	Data *UpdateTagsResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateTagsResponse) GetData() *UpdateTagsResponseData {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdateTagsResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateTagsResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponse) SetData(data *UpdateTagsResponseData) {
	u.Data = data
	u.require(updateTagsResponseFieldData)
}

func (u *UpdateTagsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTagsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateTagsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateTagsResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateTagsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateTagsResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateTagsResponseDataFieldName         = big.NewInt(1 << 0)
	updateTagsResponseDataFieldSlug         = big.NewInt(1 << 1)
	updateTagsResponseDataFieldDescription  = big.NewInt(1 << 2)
	updateTagsResponseDataFieldColor        = big.NewInt(1 << 3)
	updateTagsResponseDataFieldExtendedData = big.NewInt(1 << 4)
	updateTagsResponseDataFieldID           = big.NewInt(1 << 5)
	updateTagsResponseDataFieldCreatedAt    = big.NewInt(1 << 6)
	updateTagsResponseDataFieldUpdatedAt    = big.NewInt(1 << 7)
)

type UpdateTagsResponseData struct {
	// Tag name
	Name string `json:"name" url:"name"`
	// Tag slug (unique identifier)
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`
	// Tag description
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Hex color code
	Color *string `json:"color,omitempty" url:"color,omitempty"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	ID           string                 `json:"id" url:"id"`
	// Tag creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Tag last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateTagsResponseData) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateTagsResponseData) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

func (u *UpdateTagsResponseData) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateTagsResponseData) GetColor() *string {
	if u == nil {
		return nil
	}
	return u.Color
}

func (u *UpdateTagsResponseData) GetExtendedData() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.ExtendedData
}

func (u *UpdateTagsResponseData) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTagsResponseData) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateTagsResponseData) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateTagsResponseData) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateTagsResponseData) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetName(name string) {
	u.Name = name
	u.require(updateTagsResponseDataFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetSlug(slug *string) {
	u.Slug = slug
	u.require(updateTagsResponseDataFieldSlug)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetDescription(description *string) {
	u.Description = description
	u.require(updateTagsResponseDataFieldDescription)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetColor(color *string) {
	u.Color = color
	u.require(updateTagsResponseDataFieldColor)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetExtendedData(extendedData map[string]interface{}) {
	u.ExtendedData = extendedData
	u.require(updateTagsResponseDataFieldExtendedData)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetID(id string) {
	u.ID = id
	u.require(updateTagsResponseDataFieldID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updateTagsResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsResponseData) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updateTagsResponseDataFieldUpdatedAt)
}

func (u *UpdateTagsResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTagsResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateTagsResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateTagsResponseData) MarshalJSON() ([]byte, error) {
	type embed UpdateTagsResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateTagsResponseData) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateTagsRequestFieldID           = big.NewInt(1 << 0)
	updateTagsRequestFieldName         = big.NewInt(1 << 1)
	updateTagsRequestFieldSlug         = big.NewInt(1 << 2)
	updateTagsRequestFieldDescription  = big.NewInt(1 << 3)
	updateTagsRequestFieldColor        = big.NewInt(1 << 4)
	updateTagsRequestFieldExtendedData = big.NewInt(1 << 5)
)

type UpdateTagsRequest struct {
	// Tag ID
	ID string `json:"-" url:"-"`
	// Tag name
	Name *string `json:"name,omitempty" url:"-"`
	// Tag slug (unique identifier)
	Slug *string `json:"slug,omitempty" url:"-"`
	// Tag description
	Description *string `json:"description,omitempty" url:"-"`
	// Hex color code
	Color *string `json:"color,omitempty" url:"-"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateTagsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsRequest) SetID(id string) {
	u.ID = id
	u.require(updateTagsRequestFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsRequest) SetName(name *string) {
	u.Name = name
	u.require(updateTagsRequestFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsRequest) SetSlug(slug *string) {
	u.Slug = slug
	u.require(updateTagsRequestFieldSlug)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsRequest) SetDescription(description *string) {
	u.Description = description
	u.require(updateTagsRequestFieldDescription)
}

// SetColor sets the Color field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsRequest) SetColor(color *string) {
	u.Color = color
	u.require(updateTagsRequestFieldColor)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTagsRequest) SetExtendedData(extendedData map[string]interface{}) {
	u.ExtendedData = extendedData
	u.require(updateTagsRequestFieldExtendedData)
}
