// Code generated by Fern. DO NOT EDIT.

package foru_ms_sdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/foru-ms/go-sdk/internal"
	big "math/big"
)

var (
	deleteUsersIDFollowersSubIDRequestFieldID    = big.NewInt(1 << 0)
	deleteUsersIDFollowersSubIDRequestFieldSubID = big.NewInt(1 << 1)
)

type DeleteUsersIDFollowersSubIDRequest struct {
	// User ID
	ID string `json:"-" url:"-"`
	// Follower ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteUsersIDFollowersSubIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDFollowersSubIDRequest) SetID(id string) {
	d.ID = id
	d.require(deleteUsersIDFollowersSubIDRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDFollowersSubIDRequest) SetSubID(subID string) {
	d.SubID = subID
	d.require(deleteUsersIDFollowersSubIDRequestFieldSubID)
}

var (
	deleteUsersIDFollowingSubIDRequestFieldID    = big.NewInt(1 << 0)
	deleteUsersIDFollowingSubIDRequestFieldSubID = big.NewInt(1 << 1)
)

type DeleteUsersIDFollowingSubIDRequest struct {
	// User ID
	ID string `json:"-" url:"-"`
	// Following ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteUsersIDFollowingSubIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDFollowingSubIDRequest) SetID(id string) {
	d.ID = id
	d.require(deleteUsersIDFollowingSubIDRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDFollowingSubIDRequest) SetSubID(subID string) {
	d.SubID = subID
	d.require(deleteUsersIDFollowingSubIDRequestFieldSubID)
}

var (
	deleteUsersIDRequestFieldID = big.NewInt(1 << 0)
)

type DeleteUsersIDRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteUsersIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDRequest) SetID(id string) {
	d.ID = id
	d.require(deleteUsersIDRequestFieldID)
}

var (
	getUsersIDFollowersSubIDRequestFieldID    = big.NewInt(1 << 0)
	getUsersIDFollowersSubIDRequestFieldSubID = big.NewInt(1 << 1)
)

type GetUsersIDFollowersSubIDRequest struct {
	// User ID
	ID string `json:"-" url:"-"`
	// Follower ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUsersIDFollowersSubIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersSubIDRequest) SetID(id string) {
	g.ID = id
	g.require(getUsersIDFollowersSubIDRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersSubIDRequest) SetSubID(subID string) {
	g.SubID = subID
	g.require(getUsersIDFollowersSubIDRequestFieldSubID)
}

var (
	getUsersIDFollowingSubIDRequestFieldID    = big.NewInt(1 << 0)
	getUsersIDFollowingSubIDRequestFieldSubID = big.NewInt(1 << 1)
)

type GetUsersIDFollowingSubIDRequest struct {
	// User ID
	ID string `json:"-" url:"-"`
	// Following ID
	SubID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUsersIDFollowingSubIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingSubIDRequest) SetID(id string) {
	g.ID = id
	g.require(getUsersIDFollowingSubIDRequestFieldID)
}

// SetSubID sets the SubID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingSubIDRequest) SetSubID(subID string) {
	g.SubID = subID
	g.require(getUsersIDFollowingSubIDRequestFieldSubID)
}

var (
	getUsersIDRequestFieldID = big.NewInt(1 << 0)
)

type GetUsersIDRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUsersIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDRequest) SetID(id string) {
	g.ID = id
	g.require(getUsersIDRequestFieldID)
}

var (
	getUsersRequestFieldPage   = big.NewInt(1 << 0)
	getUsersRequestFieldLimit  = big.NewInt(1 << 1)
	getUsersRequestFieldSearch = big.NewInt(1 << 2)
)

type GetUsersRequest struct {
	Page   *int    `json:"-" url:"page,omitempty"`
	Limit  *int    `json:"-" url:"limit,omitempty"`
	Search *string `json:"-" url:"search,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUsersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersRequest) SetPage(page *int) {
	g.Page = page
	g.require(getUsersRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getUsersRequestFieldLimit)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersRequest) SetSearch(search *string) {
	g.Search = search
	g.require(getUsersRequestFieldSearch)
}

var (
	getUsersIDFollowersRequestFieldID     = big.NewInt(1 << 0)
	getUsersIDFollowersRequestFieldCursor = big.NewInt(1 << 1)
	getUsersIDFollowersRequestFieldLimit  = big.NewInt(1 << 2)
)

type GetUsersIDFollowersRequest struct {
	// User ID
	ID string `json:"-" url:"-"`
	// Pagination cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Items per page
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUsersIDFollowersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersRequest) SetID(id string) {
	g.ID = id
	g.require(getUsersIDFollowersRequestFieldID)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getUsersIDFollowersRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getUsersIDFollowersRequestFieldLimit)
}

var (
	getUsersIDFollowingRequestFieldID     = big.NewInt(1 << 0)
	getUsersIDFollowingRequestFieldCursor = big.NewInt(1 << 1)
	getUsersIDFollowingRequestFieldLimit  = big.NewInt(1 << 2)
)

type GetUsersIDFollowingRequest struct {
	// User ID
	ID string `json:"-" url:"-"`
	// Pagination cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Items per page
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUsersIDFollowingRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingRequest) SetID(id string) {
	g.ID = id
	g.require(getUsersIDFollowingRequestFieldID)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getUsersIDFollowingRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getUsersIDFollowingRequestFieldLimit)
}

var (
	deleteUsersIDFollowersSubIDResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeleteUsersIDFollowersSubIDResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteUsersIDFollowersSubIDResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteUsersIDFollowersSubIDResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteUsersIDFollowersSubIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDFollowersSubIDResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deleteUsersIDFollowersSubIDResponseFieldSuccess)
}

func (d *DeleteUsersIDFollowersSubIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteUsersIDFollowersSubIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteUsersIDFollowersSubIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteUsersIDFollowersSubIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteUsersIDFollowersSubIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteUsersIDFollowersSubIDResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deleteUsersIDFollowingSubIDResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeleteUsersIDFollowingSubIDResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteUsersIDFollowingSubIDResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteUsersIDFollowingSubIDResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteUsersIDFollowingSubIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDFollowingSubIDResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deleteUsersIDFollowingSubIDResponseFieldSuccess)
}

func (d *DeleteUsersIDFollowingSubIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteUsersIDFollowingSubIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteUsersIDFollowingSubIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteUsersIDFollowingSubIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteUsersIDFollowingSubIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteUsersIDFollowingSubIDResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deleteUsersIDResponseFieldSuccess = big.NewInt(1 << 0)
)

type DeleteUsersIDResponse struct {
	Success bool `json:"success" url:"success"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteUsersIDResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteUsersIDResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DeleteUsersIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteUsersIDResponse) SetSuccess(success bool) {
	d.Success = success
	d.require(deleteUsersIDResponseFieldSuccess)
}

func (d *DeleteUsersIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteUsersIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteUsersIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteUsersIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteUsersIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteUsersIDResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getUsersIDFollowersResponseFieldData = big.NewInt(1 << 0)
)

type GetUsersIDFollowersResponse struct {
	Data *GetUsersIDFollowersResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowersResponse) GetData() *GetUsersIDFollowersResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetUsersIDFollowersResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowersResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersResponse) SetData(data *GetUsersIDFollowersResponseData) {
	g.Data = data
	g.require(getUsersIDFollowersResponseFieldData)
}

func (g *GetUsersIDFollowersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowersResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowersResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDFollowersResponseDataFieldItems      = big.NewInt(1 << 0)
	getUsersIDFollowersResponseDataFieldNextCursor = big.NewInt(1 << 1)
	getUsersIDFollowersResponseDataFieldCount      = big.NewInt(1 << 2)
)

type GetUsersIDFollowersResponseData struct {
	Items      []*GetUsersIDFollowersResponseDataItemsItem `json:"items" url:"items"`
	NextCursor *string                                     `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	Count      int                                         `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowersResponseData) GetItems() []*GetUsersIDFollowersResponseDataItemsItem {
	if g == nil {
		return nil
	}
	return g.Items
}

func (g *GetUsersIDFollowersResponseData) GetNextCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextCursor
}

func (g *GetUsersIDFollowersResponseData) GetCount() int {
	if g == nil {
		return 0
	}
	return g.Count
}

func (g *GetUsersIDFollowersResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowersResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersResponseData) SetItems(items []*GetUsersIDFollowersResponseDataItemsItem) {
	g.Items = items
	g.require(getUsersIDFollowersResponseDataFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersResponseData) SetNextCursor(nextCursor *string) {
	g.NextCursor = nextCursor
	g.require(getUsersIDFollowersResponseDataFieldNextCursor)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersResponseData) SetCount(count int) {
	g.Count = count
	g.require(getUsersIDFollowersResponseDataFieldCount)
}

func (g *GetUsersIDFollowersResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowersResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowersResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowersResponseData) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowersResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowersResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetUsersIDFollowersResponseDataItemsItem struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowersResponseDataItemsItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowersResponseDataItemsItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

func (g *GetUsersIDFollowersResponseDataItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowersResponseDataItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowersResponseDataItemsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowersResponseDataItemsItem) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowersResponseDataItemsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowersResponseDataItemsItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDFollowersSubIDResponseFieldData = big.NewInt(1 << 0)
)

type GetUsersIDFollowersSubIDResponse struct {
	Data *GetUsersIDFollowersSubIDResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowersSubIDResponse) GetData() *GetUsersIDFollowersSubIDResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetUsersIDFollowersSubIDResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowersSubIDResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowersSubIDResponse) SetData(data *GetUsersIDFollowersSubIDResponseData) {
	g.Data = data
	g.require(getUsersIDFollowersSubIDResponseFieldData)
}

func (g *GetUsersIDFollowersSubIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowersSubIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowersSubIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowersSubIDResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowersSubIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowersSubIDResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetUsersIDFollowersSubIDResponseData struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowersSubIDResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowersSubIDResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

func (g *GetUsersIDFollowersSubIDResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowersSubIDResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowersSubIDResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowersSubIDResponseData) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowersSubIDResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowersSubIDResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDFollowingResponseFieldData = big.NewInt(1 << 0)
)

type GetUsersIDFollowingResponse struct {
	Data *GetUsersIDFollowingResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowingResponse) GetData() *GetUsersIDFollowingResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetUsersIDFollowingResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowingResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingResponse) SetData(data *GetUsersIDFollowingResponseData) {
	g.Data = data
	g.require(getUsersIDFollowingResponseFieldData)
}

func (g *GetUsersIDFollowingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowingResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowingResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDFollowingResponseDataFieldItems      = big.NewInt(1 << 0)
	getUsersIDFollowingResponseDataFieldNextCursor = big.NewInt(1 << 1)
	getUsersIDFollowingResponseDataFieldCount      = big.NewInt(1 << 2)
)

type GetUsersIDFollowingResponseData struct {
	Items      []*GetUsersIDFollowingResponseDataItemsItem `json:"items" url:"items"`
	NextCursor *string                                     `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	Count      int                                         `json:"count" url:"count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowingResponseData) GetItems() []*GetUsersIDFollowingResponseDataItemsItem {
	if g == nil {
		return nil
	}
	return g.Items
}

func (g *GetUsersIDFollowingResponseData) GetNextCursor() *string {
	if g == nil {
		return nil
	}
	return g.NextCursor
}

func (g *GetUsersIDFollowingResponseData) GetCount() int {
	if g == nil {
		return 0
	}
	return g.Count
}

func (g *GetUsersIDFollowingResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowingResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingResponseData) SetItems(items []*GetUsersIDFollowingResponseDataItemsItem) {
	g.Items = items
	g.require(getUsersIDFollowingResponseDataFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingResponseData) SetNextCursor(nextCursor *string) {
	g.NextCursor = nextCursor
	g.require(getUsersIDFollowingResponseDataFieldNextCursor)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingResponseData) SetCount(count int) {
	g.Count = count
	g.require(getUsersIDFollowingResponseDataFieldCount)
}

func (g *GetUsersIDFollowingResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowingResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowingResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowingResponseData) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowingResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowingResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetUsersIDFollowingResponseDataItemsItem struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowingResponseDataItemsItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowingResponseDataItemsItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

func (g *GetUsersIDFollowingResponseDataItemsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowingResponseDataItemsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowingResponseDataItemsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowingResponseDataItemsItem) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowingResponseDataItemsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowingResponseDataItemsItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDFollowingSubIDResponseFieldData = big.NewInt(1 << 0)
)

type GetUsersIDFollowingSubIDResponse struct {
	Data *GetUsersIDFollowingSubIDResponseData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowingSubIDResponse) GetData() *GetUsersIDFollowingSubIDResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetUsersIDFollowingSubIDResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowingSubIDResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDFollowingSubIDResponse) SetData(data *GetUsersIDFollowingSubIDResponseData) {
	g.Data = data
	g.require(getUsersIDFollowingSubIDResponseFieldData)
}

func (g *GetUsersIDFollowingSubIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowingSubIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowingSubIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowingSubIDResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowingSubIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowingSubIDResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GetUsersIDFollowingSubIDResponseData struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDFollowingSubIDResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDFollowingSubIDResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

func (g *GetUsersIDFollowingSubIDResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDFollowingSubIDResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDFollowingSubIDResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDFollowingSubIDResponseData) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDFollowingSubIDResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDFollowingSubIDResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDResponseFieldData = big.NewInt(1 << 0)
)

type GetUsersIDResponse struct {
	Data *GetUsersIDResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDResponse) GetData() *GetUsersIDResponseData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetUsersIDResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponse) SetData(data *GetUsersIDResponseData) {
	g.Data = data
	g.require(getUsersIDResponseFieldData)
}

func (g *GetUsersIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDResponseDataFieldID           = big.NewInt(1 << 0)
	getUsersIDResponseDataFieldUsername     = big.NewInt(1 << 1)
	getUsersIDResponseDataFieldDisplayName  = big.NewInt(1 << 2)
	getUsersIDResponseDataFieldBio          = big.NewInt(1 << 3)
	getUsersIDResponseDataFieldSignature    = big.NewInt(1 << 4)
	getUsersIDResponseDataFieldURL          = big.NewInt(1 << 5)
	getUsersIDResponseDataFieldPostsCount   = big.NewInt(1 << 6)
	getUsersIDResponseDataFieldThreadsCount = big.NewInt(1 << 7)
	getUsersIDResponseDataFieldIsOnline     = big.NewInt(1 << 8)
	getUsersIDResponseDataFieldLastSeenAt   = big.NewInt(1 << 9)
	getUsersIDResponseDataFieldRoles        = big.NewInt(1 << 10)
	getUsersIDResponseDataFieldExtendedData = big.NewInt(1 << 11)
	getUsersIDResponseDataFieldCreatedAt    = big.NewInt(1 << 12)
	getUsersIDResponseDataFieldUpdatedAt    = big.NewInt(1 << 13)
)

type GetUsersIDResponseData struct {
	ID       string `json:"id" url:"id"`
	Username string `json:"username" url:"username"`
	// Display name
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	// User bio
	Bio *string `json:"bio,omitempty" url:"bio,omitempty"`
	// Forum signature
	Signature *string `json:"signature,omitempty" url:"signature,omitempty"`
	// User website URL
	URL *string `json:"url,omitempty" url:"url,omitempty"`
	// Total posts by user
	PostsCount *int `json:"postsCount,omitempty" url:"postsCount,omitempty"`
	// Total threads by user
	ThreadsCount *int `json:"threadsCount,omitempty" url:"threadsCount,omitempty"`
	// Online status
	IsOnline *bool `json:"isOnline,omitempty" url:"isOnline,omitempty"`
	// Last activity timestamp
	LastSeenAt *string `json:"lastSeenAt,omitempty" url:"lastSeenAt,omitempty"`
	// User roles
	Roles []*GetUsersIDResponseDataRolesItem `json:"roles,omitempty" url:"roles,omitempty"`
	// Custom user data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	// Account creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Profile last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDResponseData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetUsersIDResponseData) GetUsername() string {
	if g == nil {
		return ""
	}
	return g.Username
}

func (g *GetUsersIDResponseData) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetUsersIDResponseData) GetBio() *string {
	if g == nil {
		return nil
	}
	return g.Bio
}

func (g *GetUsersIDResponseData) GetSignature() *string {
	if g == nil {
		return nil
	}
	return g.Signature
}

func (g *GetUsersIDResponseData) GetURL() *string {
	if g == nil {
		return nil
	}
	return g.URL
}

func (g *GetUsersIDResponseData) GetPostsCount() *int {
	if g == nil {
		return nil
	}
	return g.PostsCount
}

func (g *GetUsersIDResponseData) GetThreadsCount() *int {
	if g == nil {
		return nil
	}
	return g.ThreadsCount
}

func (g *GetUsersIDResponseData) GetIsOnline() *bool {
	if g == nil {
		return nil
	}
	return g.IsOnline
}

func (g *GetUsersIDResponseData) GetLastSeenAt() *string {
	if g == nil {
		return nil
	}
	return g.LastSeenAt
}

func (g *GetUsersIDResponseData) GetRoles() []*GetUsersIDResponseDataRolesItem {
	if g == nil {
		return nil
	}
	return g.Roles
}

func (g *GetUsersIDResponseData) GetExtendedData() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.ExtendedData
}

func (g *GetUsersIDResponseData) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetUsersIDResponseData) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetUsersIDResponseData) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDResponseData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetID(id string) {
	g.ID = id
	g.require(getUsersIDResponseDataFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetUsername(username string) {
	g.Username = username
	g.require(getUsersIDResponseDataFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetDisplayName(displayName *string) {
	g.DisplayName = displayName
	g.require(getUsersIDResponseDataFieldDisplayName)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetBio(bio *string) {
	g.Bio = bio
	g.require(getUsersIDResponseDataFieldBio)
}

// SetSignature sets the Signature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetSignature(signature *string) {
	g.Signature = signature
	g.require(getUsersIDResponseDataFieldSignature)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetURL(url *string) {
	g.URL = url
	g.require(getUsersIDResponseDataFieldURL)
}

// SetPostsCount sets the PostsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetPostsCount(postsCount *int) {
	g.PostsCount = postsCount
	g.require(getUsersIDResponseDataFieldPostsCount)
}

// SetThreadsCount sets the ThreadsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetThreadsCount(threadsCount *int) {
	g.ThreadsCount = threadsCount
	g.require(getUsersIDResponseDataFieldThreadsCount)
}

// SetIsOnline sets the IsOnline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetIsOnline(isOnline *bool) {
	g.IsOnline = isOnline
	g.require(getUsersIDResponseDataFieldIsOnline)
}

// SetLastSeenAt sets the LastSeenAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetLastSeenAt(lastSeenAt *string) {
	g.LastSeenAt = lastSeenAt
	g.require(getUsersIDResponseDataFieldLastSeenAt)
}

// SetRoles sets the Roles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetRoles(roles []*GetUsersIDResponseDataRolesItem) {
	g.Roles = roles
	g.require(getUsersIDResponseDataFieldRoles)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetExtendedData(extendedData map[string]interface{}) {
	g.ExtendedData = extendedData
	g.require(getUsersIDResponseDataFieldExtendedData)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getUsersIDResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseData) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getUsersIDResponseDataFieldUpdatedAt)
}

func (g *GetUsersIDResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDResponseData) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDResponseData) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersIDResponseDataRolesItemFieldID   = big.NewInt(1 << 0)
	getUsersIDResponseDataRolesItemFieldName = big.NewInt(1 << 1)
	getUsersIDResponseDataRolesItemFieldSlug = big.NewInt(1 << 2)
)

type GetUsersIDResponseDataRolesItem struct {
	ID   string  `json:"id" url:"id"`
	Name string  `json:"name" url:"name"`
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersIDResponseDataRolesItem) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetUsersIDResponseDataRolesItem) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetUsersIDResponseDataRolesItem) GetSlug() *string {
	if g == nil {
		return nil
	}
	return g.Slug
}

func (g *GetUsersIDResponseDataRolesItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersIDResponseDataRolesItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseDataRolesItem) SetID(id string) {
	g.ID = id
	g.require(getUsersIDResponseDataRolesItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseDataRolesItem) SetName(name string) {
	g.Name = name
	g.require(getUsersIDResponseDataRolesItemFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersIDResponseDataRolesItem) SetSlug(slug *string) {
	g.Slug = slug
	g.require(getUsersIDResponseDataRolesItemFieldSlug)
}

func (g *GetUsersIDResponseDataRolesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersIDResponseDataRolesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersIDResponseDataRolesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersIDResponseDataRolesItem) MarshalJSON() ([]byte, error) {
	type embed GetUsersIDResponseDataRolesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersIDResponseDataRolesItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersResponseFieldData = big.NewInt(1 << 0)
	getUsersResponseFieldMeta = big.NewInt(1 << 1)
)

type GetUsersResponse struct {
	Data []*GetUsersResponseDataItem `json:"data" url:"data"`
	Meta *GetUsersResponseMeta       `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersResponse) GetData() []*GetUsersResponseDataItem {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetUsersResponse) GetMeta() *GetUsersResponseMeta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetUsersResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponse) SetData(data []*GetUsersResponseDataItem) {
	g.Data = data
	g.require(getUsersResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponse) SetMeta(meta *GetUsersResponseMeta) {
	g.Meta = meta
	g.require(getUsersResponseFieldMeta)
}

func (g *GetUsersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersResponse) MarshalJSON() ([]byte, error) {
	type embed GetUsersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersResponseDataItemFieldID           = big.NewInt(1 << 0)
	getUsersResponseDataItemFieldUsername     = big.NewInt(1 << 1)
	getUsersResponseDataItemFieldDisplayName  = big.NewInt(1 << 2)
	getUsersResponseDataItemFieldBio          = big.NewInt(1 << 3)
	getUsersResponseDataItemFieldSignature    = big.NewInt(1 << 4)
	getUsersResponseDataItemFieldURL          = big.NewInt(1 << 5)
	getUsersResponseDataItemFieldPostsCount   = big.NewInt(1 << 6)
	getUsersResponseDataItemFieldThreadsCount = big.NewInt(1 << 7)
	getUsersResponseDataItemFieldIsOnline     = big.NewInt(1 << 8)
	getUsersResponseDataItemFieldLastSeenAt   = big.NewInt(1 << 9)
	getUsersResponseDataItemFieldRoles        = big.NewInt(1 << 10)
	getUsersResponseDataItemFieldExtendedData = big.NewInt(1 << 11)
	getUsersResponseDataItemFieldCreatedAt    = big.NewInt(1 << 12)
	getUsersResponseDataItemFieldUpdatedAt    = big.NewInt(1 << 13)
)

type GetUsersResponseDataItem struct {
	ID       string `json:"id" url:"id"`
	Username string `json:"username" url:"username"`
	// Display name
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	// User bio
	Bio *string `json:"bio,omitempty" url:"bio,omitempty"`
	// Forum signature
	Signature *string `json:"signature,omitempty" url:"signature,omitempty"`
	// User website URL
	URL *string `json:"url,omitempty" url:"url,omitempty"`
	// Total posts by user
	PostsCount *int `json:"postsCount,omitempty" url:"postsCount,omitempty"`
	// Total threads by user
	ThreadsCount *int `json:"threadsCount,omitempty" url:"threadsCount,omitempty"`
	// Online status
	IsOnline *bool `json:"isOnline,omitempty" url:"isOnline,omitempty"`
	// Last activity timestamp
	LastSeenAt *string `json:"lastSeenAt,omitempty" url:"lastSeenAt,omitempty"`
	// User roles
	Roles []*GetUsersResponseDataItemRolesItem `json:"roles,omitempty" url:"roles,omitempty"`
	// Custom user data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	// Account creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Profile last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersResponseDataItem) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetUsersResponseDataItem) GetUsername() string {
	if g == nil {
		return ""
	}
	return g.Username
}

func (g *GetUsersResponseDataItem) GetDisplayName() *string {
	if g == nil {
		return nil
	}
	return g.DisplayName
}

func (g *GetUsersResponseDataItem) GetBio() *string {
	if g == nil {
		return nil
	}
	return g.Bio
}

func (g *GetUsersResponseDataItem) GetSignature() *string {
	if g == nil {
		return nil
	}
	return g.Signature
}

func (g *GetUsersResponseDataItem) GetURL() *string {
	if g == nil {
		return nil
	}
	return g.URL
}

func (g *GetUsersResponseDataItem) GetPostsCount() *int {
	if g == nil {
		return nil
	}
	return g.PostsCount
}

func (g *GetUsersResponseDataItem) GetThreadsCount() *int {
	if g == nil {
		return nil
	}
	return g.ThreadsCount
}

func (g *GetUsersResponseDataItem) GetIsOnline() *bool {
	if g == nil {
		return nil
	}
	return g.IsOnline
}

func (g *GetUsersResponseDataItem) GetLastSeenAt() *string {
	if g == nil {
		return nil
	}
	return g.LastSeenAt
}

func (g *GetUsersResponseDataItem) GetRoles() []*GetUsersResponseDataItemRolesItem {
	if g == nil {
		return nil
	}
	return g.Roles
}

func (g *GetUsersResponseDataItem) GetExtendedData() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.ExtendedData
}

func (g *GetUsersResponseDataItem) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetUsersResponseDataItem) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetUsersResponseDataItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersResponseDataItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetID(id string) {
	g.ID = id
	g.require(getUsersResponseDataItemFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetUsername(username string) {
	g.Username = username
	g.require(getUsersResponseDataItemFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetDisplayName(displayName *string) {
	g.DisplayName = displayName
	g.require(getUsersResponseDataItemFieldDisplayName)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetBio(bio *string) {
	g.Bio = bio
	g.require(getUsersResponseDataItemFieldBio)
}

// SetSignature sets the Signature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetSignature(signature *string) {
	g.Signature = signature
	g.require(getUsersResponseDataItemFieldSignature)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetURL(url *string) {
	g.URL = url
	g.require(getUsersResponseDataItemFieldURL)
}

// SetPostsCount sets the PostsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetPostsCount(postsCount *int) {
	g.PostsCount = postsCount
	g.require(getUsersResponseDataItemFieldPostsCount)
}

// SetThreadsCount sets the ThreadsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetThreadsCount(threadsCount *int) {
	g.ThreadsCount = threadsCount
	g.require(getUsersResponseDataItemFieldThreadsCount)
}

// SetIsOnline sets the IsOnline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetIsOnline(isOnline *bool) {
	g.IsOnline = isOnline
	g.require(getUsersResponseDataItemFieldIsOnline)
}

// SetLastSeenAt sets the LastSeenAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetLastSeenAt(lastSeenAt *string) {
	g.LastSeenAt = lastSeenAt
	g.require(getUsersResponseDataItemFieldLastSeenAt)
}

// SetRoles sets the Roles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetRoles(roles []*GetUsersResponseDataItemRolesItem) {
	g.Roles = roles
	g.require(getUsersResponseDataItemFieldRoles)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetExtendedData(extendedData map[string]interface{}) {
	g.ExtendedData = extendedData
	g.require(getUsersResponseDataItemFieldExtendedData)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetCreatedAt(createdAt string) {
	g.CreatedAt = createdAt
	g.require(getUsersResponseDataItemFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItem) SetUpdatedAt(updatedAt string) {
	g.UpdatedAt = updatedAt
	g.require(getUsersResponseDataItemFieldUpdatedAt)
}

func (g *GetUsersResponseDataItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersResponseDataItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersResponseDataItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersResponseDataItem) MarshalJSON() ([]byte, error) {
	type embed GetUsersResponseDataItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersResponseDataItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersResponseDataItemRolesItemFieldID   = big.NewInt(1 << 0)
	getUsersResponseDataItemRolesItemFieldName = big.NewInt(1 << 1)
	getUsersResponseDataItemRolesItemFieldSlug = big.NewInt(1 << 2)
)

type GetUsersResponseDataItemRolesItem struct {
	ID   string  `json:"id" url:"id"`
	Name string  `json:"name" url:"name"`
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersResponseDataItemRolesItem) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetUsersResponseDataItemRolesItem) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetUsersResponseDataItemRolesItem) GetSlug() *string {
	if g == nil {
		return nil
	}
	return g.Slug
}

func (g *GetUsersResponseDataItemRolesItem) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersResponseDataItemRolesItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItemRolesItem) SetID(id string) {
	g.ID = id
	g.require(getUsersResponseDataItemRolesItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItemRolesItem) SetName(name string) {
	g.Name = name
	g.require(getUsersResponseDataItemRolesItemFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseDataItemRolesItem) SetSlug(slug *string) {
	g.Slug = slug
	g.require(getUsersResponseDataItemRolesItemFieldSlug)
}

func (g *GetUsersResponseDataItemRolesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersResponseDataItemRolesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersResponseDataItemRolesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersResponseDataItemRolesItem) MarshalJSON() ([]byte, error) {
	type embed GetUsersResponseDataItemRolesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersResponseDataItemRolesItem) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getUsersResponseMetaFieldTotal = big.NewInt(1 << 0)
	getUsersResponseMetaFieldPage  = big.NewInt(1 << 1)
	getUsersResponseMetaFieldLimit = big.NewInt(1 << 2)
)

type GetUsersResponseMeta struct {
	Total int `json:"total" url:"total"`
	Page  int `json:"page" url:"page"`
	Limit int `json:"limit" url:"limit"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUsersResponseMeta) GetTotal() int {
	if g == nil {
		return 0
	}
	return g.Total
}

func (g *GetUsersResponseMeta) GetPage() int {
	if g == nil {
		return 0
	}
	return g.Page
}

func (g *GetUsersResponseMeta) GetLimit() int {
	if g == nil {
		return 0
	}
	return g.Limit
}

func (g *GetUsersResponseMeta) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetUsersResponseMeta) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseMeta) SetTotal(total int) {
	g.Total = total
	g.require(getUsersResponseMetaFieldTotal)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseMeta) SetPage(page int) {
	g.Page = page
	g.require(getUsersResponseMetaFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUsersResponseMeta) SetLimit(limit int) {
	g.Limit = limit
	g.require(getUsersResponseMetaFieldLimit)
}

func (g *GetUsersResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUsersResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUsersResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUsersResponseMeta) MarshalJSON() ([]byte, error) {
	type embed GetUsersResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUsersResponseMeta) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	patchUsersIDResponseFieldData = big.NewInt(1 << 0)
)

type PatchUsersIDResponse struct {
	Data *PatchUsersIDResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PatchUsersIDResponse) GetData() *PatchUsersIDResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PatchUsersIDResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PatchUsersIDResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponse) SetData(data *PatchUsersIDResponseData) {
	p.Data = data
	p.require(patchUsersIDResponseFieldData)
}

func (p *PatchUsersIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PatchUsersIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PatchUsersIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PatchUsersIDResponse) MarshalJSON() ([]byte, error) {
	type embed PatchUsersIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PatchUsersIDResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	patchUsersIDResponseDataFieldID           = big.NewInt(1 << 0)
	patchUsersIDResponseDataFieldUsername     = big.NewInt(1 << 1)
	patchUsersIDResponseDataFieldDisplayName  = big.NewInt(1 << 2)
	patchUsersIDResponseDataFieldBio          = big.NewInt(1 << 3)
	patchUsersIDResponseDataFieldSignature    = big.NewInt(1 << 4)
	patchUsersIDResponseDataFieldURL          = big.NewInt(1 << 5)
	patchUsersIDResponseDataFieldPostsCount   = big.NewInt(1 << 6)
	patchUsersIDResponseDataFieldThreadsCount = big.NewInt(1 << 7)
	patchUsersIDResponseDataFieldIsOnline     = big.NewInt(1 << 8)
	patchUsersIDResponseDataFieldLastSeenAt   = big.NewInt(1 << 9)
	patchUsersIDResponseDataFieldRoles        = big.NewInt(1 << 10)
	patchUsersIDResponseDataFieldExtendedData = big.NewInt(1 << 11)
	patchUsersIDResponseDataFieldCreatedAt    = big.NewInt(1 << 12)
	patchUsersIDResponseDataFieldUpdatedAt    = big.NewInt(1 << 13)
)

type PatchUsersIDResponseData struct {
	ID       string `json:"id" url:"id"`
	Username string `json:"username" url:"username"`
	// Display name
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	// User bio
	Bio *string `json:"bio,omitempty" url:"bio,omitempty"`
	// Forum signature
	Signature *string `json:"signature,omitempty" url:"signature,omitempty"`
	// User website URL
	URL *string `json:"url,omitempty" url:"url,omitempty"`
	// Total posts by user
	PostsCount *int `json:"postsCount,omitempty" url:"postsCount,omitempty"`
	// Total threads by user
	ThreadsCount *int `json:"threadsCount,omitempty" url:"threadsCount,omitempty"`
	// Online status
	IsOnline *bool `json:"isOnline,omitempty" url:"isOnline,omitempty"`
	// Last activity timestamp
	LastSeenAt *string `json:"lastSeenAt,omitempty" url:"lastSeenAt,omitempty"`
	// User roles
	Roles []*PatchUsersIDResponseDataRolesItem `json:"roles,omitempty" url:"roles,omitempty"`
	// Custom user data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"extendedData,omitempty"`
	// Account creation timestamp
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// Profile last update timestamp
	UpdatedAt string `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PatchUsersIDResponseData) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchUsersIDResponseData) GetUsername() string {
	if p == nil {
		return ""
	}
	return p.Username
}

func (p *PatchUsersIDResponseData) GetDisplayName() *string {
	if p == nil {
		return nil
	}
	return p.DisplayName
}

func (p *PatchUsersIDResponseData) GetBio() *string {
	if p == nil {
		return nil
	}
	return p.Bio
}

func (p *PatchUsersIDResponseData) GetSignature() *string {
	if p == nil {
		return nil
	}
	return p.Signature
}

func (p *PatchUsersIDResponseData) GetURL() *string {
	if p == nil {
		return nil
	}
	return p.URL
}

func (p *PatchUsersIDResponseData) GetPostsCount() *int {
	if p == nil {
		return nil
	}
	return p.PostsCount
}

func (p *PatchUsersIDResponseData) GetThreadsCount() *int {
	if p == nil {
		return nil
	}
	return p.ThreadsCount
}

func (p *PatchUsersIDResponseData) GetIsOnline() *bool {
	if p == nil {
		return nil
	}
	return p.IsOnline
}

func (p *PatchUsersIDResponseData) GetLastSeenAt() *string {
	if p == nil {
		return nil
	}
	return p.LastSeenAt
}

func (p *PatchUsersIDResponseData) GetRoles() []*PatchUsersIDResponseDataRolesItem {
	if p == nil {
		return nil
	}
	return p.Roles
}

func (p *PatchUsersIDResponseData) GetExtendedData() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.ExtendedData
}

func (p *PatchUsersIDResponseData) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *PatchUsersIDResponseData) GetUpdatedAt() string {
	if p == nil {
		return ""
	}
	return p.UpdatedAt
}

func (p *PatchUsersIDResponseData) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PatchUsersIDResponseData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetID(id string) {
	p.ID = id
	p.require(patchUsersIDResponseDataFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetUsername(username string) {
	p.Username = username
	p.require(patchUsersIDResponseDataFieldUsername)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetDisplayName(displayName *string) {
	p.DisplayName = displayName
	p.require(patchUsersIDResponseDataFieldDisplayName)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetBio(bio *string) {
	p.Bio = bio
	p.require(patchUsersIDResponseDataFieldBio)
}

// SetSignature sets the Signature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetSignature(signature *string) {
	p.Signature = signature
	p.require(patchUsersIDResponseDataFieldSignature)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetURL(url *string) {
	p.URL = url
	p.require(patchUsersIDResponseDataFieldURL)
}

// SetPostsCount sets the PostsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetPostsCount(postsCount *int) {
	p.PostsCount = postsCount
	p.require(patchUsersIDResponseDataFieldPostsCount)
}

// SetThreadsCount sets the ThreadsCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetThreadsCount(threadsCount *int) {
	p.ThreadsCount = threadsCount
	p.require(patchUsersIDResponseDataFieldThreadsCount)
}

// SetIsOnline sets the IsOnline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetIsOnline(isOnline *bool) {
	p.IsOnline = isOnline
	p.require(patchUsersIDResponseDataFieldIsOnline)
}

// SetLastSeenAt sets the LastSeenAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetLastSeenAt(lastSeenAt *string) {
	p.LastSeenAt = lastSeenAt
	p.require(patchUsersIDResponseDataFieldLastSeenAt)
}

// SetRoles sets the Roles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetRoles(roles []*PatchUsersIDResponseDataRolesItem) {
	p.Roles = roles
	p.require(patchUsersIDResponseDataFieldRoles)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetExtendedData(extendedData map[string]interface{}) {
	p.ExtendedData = extendedData
	p.require(patchUsersIDResponseDataFieldExtendedData)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetCreatedAt(createdAt string) {
	p.CreatedAt = createdAt
	p.require(patchUsersIDResponseDataFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseData) SetUpdatedAt(updatedAt string) {
	p.UpdatedAt = updatedAt
	p.require(patchUsersIDResponseDataFieldUpdatedAt)
}

func (p *PatchUsersIDResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PatchUsersIDResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PatchUsersIDResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PatchUsersIDResponseData) MarshalJSON() ([]byte, error) {
	type embed PatchUsersIDResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PatchUsersIDResponseData) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	patchUsersIDResponseDataRolesItemFieldID   = big.NewInt(1 << 0)
	patchUsersIDResponseDataRolesItemFieldName = big.NewInt(1 << 1)
	patchUsersIDResponseDataRolesItemFieldSlug = big.NewInt(1 << 2)
)

type PatchUsersIDResponseDataRolesItem struct {
	ID   string  `json:"id" url:"id"`
	Name string  `json:"name" url:"name"`
	Slug *string `json:"slug,omitempty" url:"slug,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PatchUsersIDResponseDataRolesItem) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchUsersIDResponseDataRolesItem) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PatchUsersIDResponseDataRolesItem) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

func (p *PatchUsersIDResponseDataRolesItem) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PatchUsersIDResponseDataRolesItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseDataRolesItem) SetID(id string) {
	p.ID = id
	p.require(patchUsersIDResponseDataRolesItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseDataRolesItem) SetName(name string) {
	p.Name = name
	p.require(patchUsersIDResponseDataRolesItemFieldName)
}

// SetSlug sets the Slug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDResponseDataRolesItem) SetSlug(slug *string) {
	p.Slug = slug
	p.require(patchUsersIDResponseDataRolesItemFieldSlug)
}

func (p *PatchUsersIDResponseDataRolesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler PatchUsersIDResponseDataRolesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PatchUsersIDResponseDataRolesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PatchUsersIDResponseDataRolesItem) MarshalJSON() ([]byte, error) {
	type embed PatchUsersIDResponseDataRolesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PatchUsersIDResponseDataRolesItem) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	patchUsersIDRequestFieldID           = big.NewInt(1 << 0)
	patchUsersIDRequestFieldDisplayName  = big.NewInt(1 << 1)
	patchUsersIDRequestFieldBio          = big.NewInt(1 << 2)
	patchUsersIDRequestFieldSignature    = big.NewInt(1 << 3)
	patchUsersIDRequestFieldUsername     = big.NewInt(1 << 4)
	patchUsersIDRequestFieldEmail        = big.NewInt(1 << 5)
	patchUsersIDRequestFieldPassword     = big.NewInt(1 << 6)
	patchUsersIDRequestFieldURL          = big.NewInt(1 << 7)
	patchUsersIDRequestFieldExtendedData = big.NewInt(1 << 8)
	patchUsersIDRequestFieldRoles        = big.NewInt(1 << 9)
)

type PatchUsersIDRequest struct {
	ID string `json:"-" url:"-"`
	// Display name
	DisplayName *string `json:"displayName,omitempty" url:"-"`
	// User bio
	Bio *string `json:"bio,omitempty" url:"-"`
	// Forum signature
	Signature *string `json:"signature,omitempty" url:"-"`
	// Username (letters, numbers, underscores, hyphens)
	Username *string `json:"username,omitempty" url:"-"`
	// Email address
	Email *string `json:"email,omitempty" url:"-"`
	// New password
	Password *string `json:"password,omitempty" url:"-"`
	// Website URL
	URL *string `json:"url,omitempty" url:"-"`
	// Extended data
	ExtendedData map[string]interface{} `json:"extendedData,omitempty" url:"-"`
	// Role slugs (admin only)
	Roles []string `json:"roles,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PatchUsersIDRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetID(id string) {
	p.ID = id
	p.require(patchUsersIDRequestFieldID)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetDisplayName(displayName *string) {
	p.DisplayName = displayName
	p.require(patchUsersIDRequestFieldDisplayName)
}

// SetBio sets the Bio field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetBio(bio *string) {
	p.Bio = bio
	p.require(patchUsersIDRequestFieldBio)
}

// SetSignature sets the Signature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetSignature(signature *string) {
	p.Signature = signature
	p.require(patchUsersIDRequestFieldSignature)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetUsername(username *string) {
	p.Username = username
	p.require(patchUsersIDRequestFieldUsername)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetEmail(email *string) {
	p.Email = email
	p.require(patchUsersIDRequestFieldEmail)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetPassword(password *string) {
	p.Password = password
	p.require(patchUsersIDRequestFieldPassword)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetURL(url *string) {
	p.URL = url
	p.require(patchUsersIDRequestFieldURL)
}

// SetExtendedData sets the ExtendedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetExtendedData(extendedData map[string]interface{}) {
	p.ExtendedData = extendedData
	p.require(patchUsersIDRequestFieldExtendedData)
}

// SetRoles sets the Roles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchUsersIDRequest) SetRoles(roles []string) {
	p.Roles = roles
	p.require(patchUsersIDRequestFieldRoles)
}
