// Code generated by Fern. DO NOT EDIT.

package search

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) Search(
	ctx context.Context,
	opts ...option.RequestOption,
) (*foru_ms_sdk.SearchSearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
