// Code generated by Fern. DO NOT EDIT.

package auth

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) Register(
	ctx context.Context,
	request *foru_ms_sdk.PostAuthRegisterRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostAuthRegisterResponse, error) {
	response, err := c.WithRawResponse.Register(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Login(
	ctx context.Context,
	request *foru_ms_sdk.PostAuthLoginRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostAuthLoginResponse, error) {
	response, err := c.WithRawResponse.Login(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetCurrentUser(
	ctx context.Context,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetAuthMeResponse, error) {
	response, err := c.WithRawResponse.GetCurrentUser(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) RequestPasswordReset(
	ctx context.Context,
	request *foru_ms_sdk.PostAuthForgotPasswordRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostAuthForgotPasswordResponse, error) {
	response, err := c.WithRawResponse.RequestPasswordReset(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ResetPassword(
	ctx context.Context,
	request *foru_ms_sdk.PostAuthResetPasswordRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostAuthResetPasswordResponse, error) {
	response, err := c.WithRawResponse.ResetPassword(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
