// Code generated by Fern. DO NOT EDIT.

package reports

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a paginated list of reports. Use cursor for pagination.
func (c *Client) List(
	ctx context.Context,
	request *foru_ms_sdk.ListReportsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.ReportListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new report.
func (c *Client) Create(
	ctx context.Context,
	request *foru_ms_sdk.CreateReportsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.ReportResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a report by ID or slug (if supported).
func (c *Client) Retrieve(
	ctx context.Context,
	request *foru_ms_sdk.RetrieveReportsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.ReportResponse, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently delete a report.
func (c *Client) Delete(
	ctx context.Context,
	request *foru_ms_sdk.DeleteReportsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.SuccessResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an existing report. Only provided fields will be modified.
func (c *Client) Update(
	ctx context.Context,
	request *foru_ms_sdk.UpdateReportsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.UpdateReportsResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
