// Code generated by Fern. DO NOT EDIT.

package webhooks_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	client "github.com/foru-ms/go-sdk/client"
	option "github.com/foru-ms/go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWebhooksListAllWebhooksWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetWebhooksRequest{}
	_, invocationErr := client.Webhooks.ListAllWebhooks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksListAllWebhooksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksListAllWebhooksWithWireMock", "GET", "/webhooks", nil, 1)
}

func TestWebhooksCreateAWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.PostWebhooksRequest{
		Name: "name",
		URL:  "url",
		Events: []string{
			"events",
		},
	}
	_, invocationErr := client.Webhooks.CreateAWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksCreateAWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksCreateAWebhookWithWireMock", "POST", "/webhooks", nil, 1)
}

func TestWebhooksGetAWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetWebhooksIDRequest{
		ID: "id",
	}
	_, invocationErr := client.Webhooks.GetAWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksGetAWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksGetAWebhookWithWireMock", "GET", "/webhooks/id", nil, 1)
}

func TestWebhooksDeleteAWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.DeleteWebhooksIDRequest{
		ID: "id",
	}
	_, invocationErr := client.Webhooks.DeleteAWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksDeleteAWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksDeleteAWebhookWithWireMock", "DELETE", "/webhooks/id", nil, 1)
}

func TestWebhooksListWebhookDeliveriesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetWebhooksIDDeliveriesRequest{
		ID: "id",
	}
	_, invocationErr := client.Webhooks.ListWebhookDeliveries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksListWebhookDeliveriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksListWebhookDeliveriesWithWireMock", "GET", "/webhooks/id/deliveries", nil, 1)
}

func TestWebhooksGetADeliveryFromWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetWebhooksIDDeliveriesSubIDRequest{
		ID:    "id",
		SubID: "subId",
	}
	_, invocationErr := client.Webhooks.GetADeliveryFromWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksGetADeliveryFromWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksGetADeliveryFromWebhookWithWireMock", "GET", "/webhooks/id/deliveries/subId", nil, 1)
}

func TestWebhooksDeleteADeliveryFromWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.DeleteWebhooksIDDeliveriesSubIDRequest{
		ID:    "id",
		SubID: "subId",
	}
	_, invocationErr := client.Webhooks.DeleteADeliveryFromWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksDeleteADeliveryFromWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksDeleteADeliveryFromWebhookWithWireMock", "DELETE", "/webhooks/id/deliveries/subId", nil, 1)
}
