// Code generated by Fern. DO NOT EDIT.

package threads

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListAllThreads(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsResponse, error) {
	response, err := c.WithRawResponse.ListAllThreads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateAThread(
	ctx context.Context,
	request *foru_ms_sdk.PostThreadsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostThreadsResponse, error) {
	response, err := c.WithRawResponse.CreateAThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAThread(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDResponse, error) {
	response, err := c.WithRawResponse.GetAThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAThread(
	ctx context.Context,
	request *foru_ms_sdk.DeleteThreadsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteThreadsIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateAThread(
	ctx context.Context,
	request *foru_ms_sdk.PatchThreadsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PatchThreadsIDResponse, error) {
	response, err := c.WithRawResponse.UpdateAThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListThreadPosts(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDPostsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDPostsResponse, error) {
	response, err := c.WithRawResponse.ListThreadPosts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAPostFromThread(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDPostsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDPostsSubIDResponse, error) {
	response, err := c.WithRawResponse.GetAPostFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAPostFromThread(
	ctx context.Context,
	request *foru_ms_sdk.DeleteThreadsIDPostsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteThreadsIDPostsSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAPostFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListThreadReactions(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDReactionsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDReactionsResponse, error) {
	response, err := c.WithRawResponse.ListThreadReactions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateAReactionInThread(
	ctx context.Context,
	request *foru_ms_sdk.PostThreadsIDReactionsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostThreadsIDReactionsResponse, error) {
	response, err := c.WithRawResponse.CreateAReactionInThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Removes the authenticated user's reaction. No subId needed.
func (c *Client) RemoveYourReactionFromThread(
	ctx context.Context,
	request *foru_ms_sdk.DeleteThreadsIDReactionsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteThreadsIDReactionsResponse, error) {
	response, err := c.WithRawResponse.RemoveYourReactionFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAReactionFromThread(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDReactionsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDReactionsSubIDResponse, error) {
	response, err := c.WithRawResponse.GetAReactionFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAReactionFromThread(
	ctx context.Context,
	request *foru_ms_sdk.DeleteThreadsIDReactionsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteThreadsIDReactionsSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAReactionFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListThreadSubscribers(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDSubscribersRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDSubscribersResponse, error) {
	response, err := c.WithRawResponse.ListThreadSubscribers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetASubscriberFromThread(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDSubscribersSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDSubscribersSubIDResponse, error) {
	response, err := c.WithRawResponse.GetASubscriberFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteASubscriberFromThread(
	ctx context.Context,
	request *foru_ms_sdk.DeleteThreadsIDSubscribersSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteThreadsIDSubscribersSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteASubscriberFromThread(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetThreadPoll(
	ctx context.Context,
	request *foru_ms_sdk.GetThreadsIDPollRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetThreadsIDPollResponse, error) {
	response, err := c.WithRawResponse.GetThreadPoll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateThreadPoll(
	ctx context.Context,
	request *foru_ms_sdk.PostThreadsIDPollRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostThreadsIDPollResponse, error) {
	response, err := c.WithRawResponse.CreateThreadPoll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateThreadPoll(
	ctx context.Context,
	request *foru_ms_sdk.PatchThreadsIDPollRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PatchThreadsIDPollResponse, error) {
	response, err := c.WithRawResponse.UpdateThreadPoll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
