// Code generated by Fern. DO NOT EDIT.

package provisioning_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	client "github.com/foru-ms/go-sdk/client"
	option "github.com/foru-ms/go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestProvisioningListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.ListProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningListWithWireMock", "GET", "/provisioning/instances", nil, 1)
}

func TestProvisioningCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.CreateInstance{
		ProvisioningKey: "x-provisioning-key",
		Name:            "name",
		Handle:          "handle",
	}
	_, invocationErr := client.Provisioning.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningCreateWithWireMock", "POST", "/provisioning/instances", nil, 1)
}

func TestProvisioningUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.UpdateInstance{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
	}
	_, invocationErr := client.Provisioning.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningUpdateWithWireMock", "PUT", "/provisioning/instances", nil, 1)
}

func TestProvisioningDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.DeleteInstance{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
	}
	_, invocationErr := client.Provisioning.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningDeleteWithWireMock", "DELETE", "/provisioning/instances", nil, 1)
}

func TestProvisioningGetBillingWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetBillingProvisioningRequest{
		Handle:          "handle",
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.GetBilling(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningGetBillingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningGetBillingWithWireMock", "GET", "/provisioning/instances/billing", map[string]string{"handle": "handle"}, 1)
}

func TestProvisioningChangePlanWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.UpgradeInstance{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		Plan:            foru_ms_sdk.UpgradeInstancePlanFree,
	}
	_, invocationErr := client.Provisioning.ChangePlan(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningChangePlanWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningChangePlanWithWireMock", "POST", "/provisioning/instances/billing", nil, 1)
}

func TestProvisioningRegenerateAPIKeyWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.RegenerateAPIKeyProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
	}
	_, invocationErr := client.Provisioning.RegenerateAPIKey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningRegenerateAPIKeyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningRegenerateAPIKeyWithWireMock", "POST", "/provisioning/instances/api-key", nil, 1)
}

func TestProvisioningGetUsageWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetUsageProvisioningRequest{
		Handle:          "handle",
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.GetUsage(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningGetUsageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningGetUsageWithWireMock", "GET", "/provisioning/instances/usage", map[string]string{"handle": "handle"}, 1)
}

func TestProvisioningListTeamWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.ListTeamProvisioningRequest{
		Handle:          "handle",
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.ListTeam(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningListTeamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningListTeamWithWireMock", "GET", "/provisioning/instances/team", map[string]string{"handle": "handle"}, 1)
}

func TestProvisioningInviteTeamWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.InviteTeamProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		Members: []*foru_ms_sdk.InviteTeamProvisioningRequestMembersItem{
			&foru_ms_sdk.InviteTeamProvisioningRequestMembersItem{
				Email: "email",
			},
		},
	}
	_, invocationErr := client.Provisioning.InviteTeam(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningInviteTeamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningInviteTeamWithWireMock", "POST", "/provisioning/instances/team", nil, 1)
}

func TestProvisioningRemoveTeamMemberWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.RemoveTeamMemberProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		Email:           "email",
	}
	_, invocationErr := client.Provisioning.RemoveTeamMember(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningRemoveTeamMemberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningRemoveTeamMemberWithWireMock", "DELETE", "/provisioning/instances/team", nil, 1)
}

func TestProvisioningListDomainsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.ListDomainsProvisioningRequest{
		Handle:          "handle",
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.ListDomains(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningListDomainsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningListDomainsWithWireMock", "GET", "/provisioning/instances/domains", map[string]string{"handle": "handle"}, 1)
}

func TestProvisioningAddDomainWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.AddDomainProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		Name:            "name",
	}
	_, invocationErr := client.Provisioning.AddDomain(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningAddDomainWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningAddDomainWithWireMock", "POST", "/provisioning/instances/domains", nil, 1)
}

func TestProvisioningRemoveDomainWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.RemoveDomainProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		Name:            "name",
	}
	_, invocationErr := client.Provisioning.RemoveDomain(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningRemoveDomainWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningRemoveDomainWithWireMock", "DELETE", "/provisioning/instances/domains", nil, 1)
}

func TestProvisioningExportDataWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.ExportDataProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
	}
	_, invocationErr := client.Provisioning.ExportData(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningExportDataWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningExportDataWithWireMock", "POST", "/provisioning/instances/export", nil, 1)
}

func TestProvisioningListWebhooksWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.ListWebhooksProvisioningRequest{
		Handle:          "handle",
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.ListWebhooks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningListWebhooksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningListWebhooksWithWireMock", "GET", "/provisioning/instances/webhooks", map[string]string{"handle": "handle"}, 1)
}

func TestProvisioningCreateWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.CreateWebhookProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		URL:             "url",
		Events: []string{
			"events",
		},
	}
	_, invocationErr := client.Provisioning.CreateWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningCreateWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningCreateWebhookWithWireMock", "POST", "/provisioning/instances/webhooks", nil, 1)
}

func TestProvisioningUpdateWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.UpdateWebhookProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		WebhookID:       "webhookId",
	}
	_, invocationErr := client.Provisioning.UpdateWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningUpdateWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningUpdateWebhookWithWireMock", "PUT", "/provisioning/instances/webhooks", nil, 1)
}

func TestProvisioningDeleteWebhookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.DeleteWebhookProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		WebhookID:       "webhookId",
	}
	_, invocationErr := client.Provisioning.DeleteWebhook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningDeleteWebhookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningDeleteWebhookWithWireMock", "DELETE", "/provisioning/instances/webhooks", nil, 1)
}

func TestProvisioningGetOwnershipWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.GetOwnershipProvisioningRequest{
		Handle:          "handle",
		ProvisioningKey: "x-provisioning-key",
	}
	_, invocationErr := client.Provisioning.GetOwnership(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningGetOwnershipWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningGetOwnershipWithWireMock", "GET", "/provisioning/instances/ownership", map[string]string{"handle": "handle"}, 1)
}

func TestProvisioningTransferOwnershipWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.TransferOwnershipProvisioningRequest{
		ProvisioningKey: "x-provisioning-key",
		Handle:          "handle",
		NewOwnerEmail:   "newOwnerEmail",
	}
	_, invocationErr := client.Provisioning.TransferOwnership(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningTransferOwnershipWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningTransferOwnershipWithWireMock", "POST", "/provisioning/instances/ownership", nil, 1)
}

func TestProvisioningRegisterWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.RegisterProvisioningRequest{
		Email:    "email",
		Password: "password",
	}
	_, invocationErr := client.Provisioning.Register(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningRegisterWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningRegisterWithWireMock", "POST", "/provisioning/register", nil, 1)
}

func TestProvisioningLoginWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.LoginProvisioningRequest{
		Email:    "email",
		Password: "password",
	}
	_, invocationErr := client.Provisioning.Login(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProvisioningLoginWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProvisioningLoginWithWireMock", "POST", "/provisioning/login", nil, 1)
}
