// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListAllUsers(
	ctx context.Context,
	request *foru_ms_sdk.GetUsersRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetUsersResponse, error) {
	response, err := c.WithRawResponse.ListAllUsers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAUser(
	ctx context.Context,
	request *foru_ms_sdk.GetUsersIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetUsersIDResponse, error) {
	response, err := c.WithRawResponse.GetAUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAUser(
	ctx context.Context,
	request *foru_ms_sdk.DeleteUsersIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteUsersIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateAUser(
	ctx context.Context,
	request *foru_ms_sdk.PatchUsersIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PatchUsersIDResponse, error) {
	response, err := c.WithRawResponse.UpdateAUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListUserFollowers(
	ctx context.Context,
	request *foru_ms_sdk.GetUsersIDFollowersRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetUsersIDFollowersResponse, error) {
	response, err := c.WithRawResponse.ListUserFollowers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAFollowerFromUser(
	ctx context.Context,
	request *foru_ms_sdk.GetUsersIDFollowersSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetUsersIDFollowersSubIDResponse, error) {
	response, err := c.WithRawResponse.GetAFollowerFromUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAFollowerFromUser(
	ctx context.Context,
	request *foru_ms_sdk.DeleteUsersIDFollowersSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteUsersIDFollowersSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAFollowerFromUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListUserFollowing(
	ctx context.Context,
	request *foru_ms_sdk.GetUsersIDFollowingRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetUsersIDFollowingResponse, error) {
	response, err := c.WithRawResponse.ListUserFollowing(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAFollowingFromUser(
	ctx context.Context,
	request *foru_ms_sdk.GetUsersIDFollowingSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetUsersIDFollowingSubIDResponse, error) {
	response, err := c.WithRawResponse.GetAFollowingFromUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAFollowingFromUser(
	ctx context.Context,
	request *foru_ms_sdk.DeleteUsersIDFollowingSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeleteUsersIDFollowingSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAFollowingFromUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
