// Code generated by Fern. DO NOT EDIT.

package posts

import (
	context "context"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	core "github.com/foru-ms/go-sdk/core"
	internal "github.com/foru-ms/go-sdk/internal"
	option "github.com/foru-ms/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListAllPosts(
	ctx context.Context,
	request *foru_ms_sdk.GetPostsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetPostsResponse, error) {
	response, err := c.WithRawResponse.ListAllPosts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateAPost(
	ctx context.Context,
	request *foru_ms_sdk.PostPostsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostPostsResponse, error) {
	response, err := c.WithRawResponse.CreateAPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAPost(
	ctx context.Context,
	request *foru_ms_sdk.GetPostsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetPostsIDResponse, error) {
	response, err := c.WithRawResponse.GetAPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAPost(
	ctx context.Context,
	request *foru_ms_sdk.DeletePostsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeletePostsIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdateAPost(
	ctx context.Context,
	request *foru_ms_sdk.PatchPostsIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PatchPostsIDResponse, error) {
	response, err := c.WithRawResponse.UpdateAPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListPostReactions(
	ctx context.Context,
	request *foru_ms_sdk.GetPostsIDReactionsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetPostsIDReactionsResponse, error) {
	response, err := c.WithRawResponse.ListPostReactions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateAReactionInPost(
	ctx context.Context,
	request *foru_ms_sdk.PostPostsIDReactionsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.PostPostsIDReactionsResponse, error) {
	response, err := c.WithRawResponse.CreateAReactionInPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Removes the authenticated user's reaction. No subId needed.
func (c *Client) RemoveYourReactionFromPost(
	ctx context.Context,
	request *foru_ms_sdk.DeletePostsIDReactionsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeletePostsIDReactionsResponse, error) {
	response, err := c.WithRawResponse.RemoveYourReactionFromPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAReactionFromPost(
	ctx context.Context,
	request *foru_ms_sdk.GetPostsIDReactionsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetPostsIDReactionsSubIDResponse, error) {
	response, err := c.WithRawResponse.GetAReactionFromPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAReactionFromPost(
	ctx context.Context,
	request *foru_ms_sdk.DeletePostsIDReactionsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeletePostsIDReactionsSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAReactionFromPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListPostPosts(
	ctx context.Context,
	request *foru_ms_sdk.GetPostsIDPostsRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetPostsIDPostsResponse, error) {
	response, err := c.WithRawResponse.ListPostPosts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetAPostFromPost(
	ctx context.Context,
	request *foru_ms_sdk.GetPostsIDPostsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.GetPostsIDPostsSubIDResponse, error) {
	response, err := c.WithRawResponse.GetAPostFromPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteAPostFromPost(
	ctx context.Context,
	request *foru_ms_sdk.DeletePostsIDPostsSubIDRequest,
	opts ...option.RequestOption,
) (*foru_ms_sdk.DeletePostsIDPostsSubIDResponse, error) {
	response, err := c.WithRawResponse.DeleteAPostFromPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
