// Code generated by Fern. DO NOT EDIT.

package ss_os_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	foru_ms_sdk "github.com/foru-ms/go-sdk"
	client "github.com/foru-ms/go-sdk/client"
	option "github.com/foru-ms/go-sdk/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSsOsListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.ListSsOsRequest{}
	_, invocationErr := client.SsOs.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSsOsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSsOsListWithWireMock", "GET", "/sso", nil, 1)
}

func TestSsOsCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.CreateSsOsRequest{
		Provider: foru_ms_sdk.CreateSsOsRequestProviderOkta,
		Domain:   "domain",
		Config: map[string]any{
			"key": "value",
		},
	}
	_, invocationErr := client.SsOs.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSsOsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSsOsCreateWithWireMock", "POST", "/sso", nil, 1)
}

func TestSsOsRetrieveWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.RetrieveSsOsRequest{
		ID: "id",
	}
	_, invocationErr := client.SsOs.Retrieve(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSsOsRetrieveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSsOsRetrieveWithWireMock", "GET", "/sso/id", nil, 1)
}

func TestSsOsDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.DeleteSsOsRequest{
		ID: "id",
	}
	_, invocationErr := client.SsOs.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSsOsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSsOsDeleteWithWireMock", "DELETE", "/sso/id", nil, 1)
}

func TestSsOsUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &foru_ms_sdk.UpdateSsOsRequest{
		ID: "id",
	}
	_, invocationErr := client.SsOs.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSsOsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSsOsUpdateWithWireMock", "PATCH", "/sso/id", nil, 1)
}
